# Lot 1 (Cap Bon) — 8 restaurants/cafés + 1 atelier faire-part (7 démos retirées le 30/09/2026).
# Données relevées sur fiches publiques (lacarte.menu, plurielle.tn, restaurantguru.com) le 30/09/2026.
import sys, os; sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from gen_lot1 import build_resto, build_event, build_invit, ph

PH = ph()
def rt(score, count, label, src, url): return dict(score=score, count=count, label=label, src=src, url=url)
def hrs_all(h): return [('Lundi – Dimanche', h)]
DEF_FEAT = lambda extra: extra + [
    ('calendar', 'Réservation sur WhatsApp', 'La demande de table arrive pré-remplie ; vous confirmez quand vous êtes disponible.'),
    ('chat', 'Réponses automatiques', 'Horaires, accès, plats du jour : les questions fréquentes répondues même en plein service.'),
]
def resto(**S):
    n = S['name']
    S.setdefault('font', 'fraunces')
    S.setdefault('wa_msg', f"Bonjour {n}, je souhaite réserver une table.")
    S.setdefault('form_intro', f"Bonjour {n}, je souhaite réserver une table :")
    S.setdefault('book_note', f"La table est confirmée par le restaurant (WhatsApp ou téléphone). Groupes et événements sur demande {PH}.")
    S.setdefault('email', '')
    S.setdefault('gal_h2', 'L’ambiance, en images')
    S.setdefault('about_eyebrow', 'La maison')
    build_resto(S)

# 1 ------------------------------------------------------------------ DAR MRAD (Nabeul)
resto(slug='dar-mrad-nabeul', name='Dar Mrad', mark='M', font='fraunces',
 theme=dict(accent='#9a3b25', accent2='#e9b44c', soft='#f7e7dc', bg='#fcf8f3', bgalt='#f4ece2', ink='#2a150e'),
 title='Dar Mrad — Cuisine tunisienne maison à Nabeul (démo)',
 desc='Dar Mrad, restaurant de cuisine tunisienne à Nabeul : kamounia, poulet grillé, soupes. Carte, réservation WhatsApp, accès.',
 tagline='Cuisine tunisienne · Nabeul', eyebrow='Restaurant · Nabeul',
 h1='La cuisine tunisienne de maison, au cœur de Nabeul',
 lead='Kamounia, poulet grillé, soupe à la tomate et thé à la menthe : des plats simples et généreux, appréciés par plus de 330 clients en ligne.',
 hero_alt='Salade mechouia et plats tunisiens (photo d’ambiance)',
 facts=[('Nabeul', 'Av. Mongi Slim'), ('Midi', f'12h – 17h · lun.–sam.')],
 about_h2='Une table familiale, sans chichi',
 about_p=['Dar Mrad sert une cuisine tunisienne de tous les jours, comme à la maison : plats mijotés, grillades et soupes.',
          f'Spécialités citées en ligne : kamounia, poulet grillé, soupe crème de tomates, paella, thé vert à la menthe. Plats du jour et formules {PH}.'],
 about_img='about', about_alt='Céramiste peignant une assiette à Nabeul (photo d’ambiance)',
 chips=['Cuisine tunisienne', 'Plats mijotés', 'Grillades', 'Thé à la menthe'],
 menu_h2='Les classiques de la maison', menu_lead='Une sélection des plats cités sur les fiches publiques du restaurant. La carte complète sera ajoutée avec vous.',
 dishes=[dict(img='d1', alt='Plat de couscous tunisien', name='Kamounia', desc='Ragoût au cumin, spécialité citée sur la carte en ligne.', tag='Carte en ligne'),
         dict(img='d2', alt='Couscous au poulet', name='Poulet grillé', desc='Servi avec accompagnements du jour.', tag='Carte en ligne'),
         dict(img='d3', alt='Salade mechouia', name='Salade mechouia', desc='Poivrons et tomates grillés, huile d’olive.', tag='Exemple'),
         dict(img='d4', alt='Briks tunisiennes', name='Brik', desc='Feuille croustillante, œuf et thon.', tag='Exemple')],
 menu_cats=['Soupes', 'Plats mijotés', 'Grillades', 'Paella', 'Boissons chaudes', 'Thé'],
 features=DEF_FEAT([('food', 'Plats du jour', 'Publiés chaque matin sur le site et en statut WhatsApp.'), ('truck', 'À emporter', f'Commande à récupérer sur place {PH}.')]),
 gal_lead='Nabeul, sa médina, ses souks et sa poterie.',
 gallery=[('g1', 'Souk de Nabeul'), ('g2', 'Poteries de Nabeul'), ('g3', 'Souk couvert de Nabeul'), ('g4', 'Potier à Nabeul'), ('hero', 'Plats tunisiens'), ('d3', 'Salade mechouia')],
 wa='21620859220', wa_disp='+216 20 859 220', tels=['+216 20 859 220'],
 address='Av. Mongi Slim, 8000 Nabeul', map_q='36.452895,10.743317', map_z=17,
 loc_h2='En plein centre de Nabeul', loc_p='À quelques minutes à pied du souk et de la médina.',
 hours=[('Lundi – Samedi', f'12:00 – 17:00 {PH}'), ('Dimanche', PH)], hours_short=f'Lun.–sam. 12h–17h {PH}',
 social=[('Facebook', 'www.facebook.com/nabeul1973')],
 ratings=[rt('4.0', 337, 'note moyenne', 'lacarte.menu', 'https://lacarte.menu/restaurants/tunisia/dar-mrad')])

# 2 ------------------------------------------------------------------ LE PÊCHEUR (Hammamet)
resto(slug='le-pecheur-hammamet', name='Restaurant Le Pêcheur', mark='P', font='dmserif',
 theme=dict(accent='#155e75', accent2='#f2b541', soft='#dff1f6', bg='#f9fbfb', bgalt='#eaf2f3', ink='#0c2230'),
 title='Restaurant Le Pêcheur — Poisson & fruits de mer face à la médina de Hammamet (démo)',
 desc='Le Pêcheur, Hammamet : poisson grillé, fruits de mer, couscous au mérou, face à la médina. Carte, réservation WhatsApp, accès.',
 tagline='Poisson & fruits de mer · Hammamet', eyebrow='Restaurant · face à la médina de Hammamet',
 h1='Le poisson du jour, face à la médina de Hammamet',
 lead='Grillades de la mer, moules, couscous au mérou et « Délice du Pêcheur » : une adresse notée 4,4/5 par plus de 400 clients.',
 hero_alt='Plage et médina de Hammamet (photo d’ambiance)',
 facts=[('Médina', 'Av. de la République'), ('11h – minuit', 'tous les jours')],
 about_h2='Une adresse de la mer, au centre de Hammamet',
 about_p=['Le Pêcheur accueille ses clients face à la médina, avec une carte tournée vers la mer : poisson grillé, crevettes, calamars et moules.',
          f'Également cités par les clients : ojja merguez, bricks (thon, fromage, crevettes), salades caprese et méchouia, grillades mixtes. Arrivage et prix du poisson au kilo {PH}.'],
 about_img='about', about_alt='Plateau de poissons et fruits de mer grillés (photo d’ambiance)',
 chips=['Poisson grillé', 'Fruits de mer', 'Couscous au mérou', 'Face à la médina'],
 menu_h2='Les incontournables du Pêcheur', menu_lead='Plats relevés sur les fiches et avis publics. Poisson du jour selon arrivage.',
 dishes=[dict(img='d1', alt='Assiette de poissons et fruits de mer grillés', name='Délice du Pêcheur', desc='Assortiment de la mer, spécialité de la maison.', tag='Carte en ligne'),
         dict(img='d2', alt='Ojja aux merguez', name='Ojja merguez', desc='Œufs, sauce tomate pimentée et merguez.', tag='Carte en ligne'),
         dict(img='d3', alt='Couscous au poisson', name='Couscous au mérou', desc='Cité à plusieurs reprises dans les avis clients.', tag='Avis clients'),
         dict(img='d4', alt='Briks tunisiennes', name='Bricks thon / crevettes', desc='Croustillantes, en entrée.', tag='Avis clients')],
 menu_cats=['Entrées & bricks', 'Salades', 'Poisson grillé au kilo', 'Moules & crevettes', 'Couscous', 'Grillades'],
 features=DEF_FEAT([('fire', 'Poisson du jour', 'Arrivage affiché chaque jour, prix au kilo mis à jour en 1 minute.'), ('map', 'Face à la médina', 'Itinéraire, parking et horaires visibles en un clic.')]),
 gal_lead='Hammamet : la médina, le fort et la plage, à deux pas.',
 gallery=[('g1', 'Vue sur la mer depuis le fort de Hammamet'), ('g2', 'Médina de Hammamet'), ('g3', 'Barque sur la plage de Hammamet'), ('g4', 'Calamars grillés'), ('g5', 'Remparts de Hammamet'), ('about', 'Poissons grillés')],
 wa='21672282434', wa_disp='+216 72 282 434', wa_note='ligne fixe : numéro WhatsApp à confirmer', tels=['+216 72 282 434'],
 address='Avenue de la République, face à la médina, 8050 Hammamet', map_q='36.39533,10.61397', map_z=17,
 loc_h2='Face à la médina', loc_p='Sur l’avenue de la République, à quelques pas des remparts et de la plage.',
 hours=hrs_all('11:00 – 00:00'), hours_short='Tous les jours 11h – minuit',
 ratings=[rt('4.4', 436, 'note moyenne', 'lacarte.menu', 'https://lacarte.menu/restaurants/hammamet/le-pecheur-10'),
          rt('4.3', 59, 'note moyenne', 'plurielle.tn', 'https://plurielle.tn/pro/nabeul/restaurant-le-pecheur/')])

# 4 ------------------------------------------------------------------ BRIDGE CAFÉ (Hammamet)
resto(slug='bridge-cafe-hammamet', name='Bridge Café', mark='B', font='jakarta',
 theme=dict(accent='#6b4226', accent2='#e0a458', soft='#f3e8dd', bg='#fbf8f4', bgalt='#f2ebe3', ink='#23160e'),
 title='Bridge Café — Café, crêpes & glaces, avenue de la République, Hammamet (démo)',
 desc='Bridge Café, Hammamet : expresso, cappuccino, crêpes, glaces, jus et omelettes. Menu QR, commande à emporter via WhatsApp.',
 tagline='Café · crêpes · glaces · Hammamet', eyebrow='Café · avenue de la République, Hammamet',
 h1='Un café, une crêpe, et la vie de Hammamet qui passe',
 lead='Expresso, cappuccino, crêpes, glaces et jus frais à petit prix. Plus de 1 100 avis clients en ligne.',
 hero_alt='Médina de Hammamet (photo d’ambiance)',
 facts=[('Centre-ville', 'Av. de la République'), ('$ – $$', 'petit budget')],
 about_h2='Le rendez-vous du centre-ville',
 about_p=['Sur l’avenue de la République, Bridge Café est une halte simple et conviviale pour un café, un goûter ou un petit-déjeuner.',
          f'Cités en ligne : expresso, cappuccino, crêpes, glaces, jus de fruits, omelettes. Horaires d’ouverture {PH}.'],
 about_img='about', about_alt='Cappuccino et biscuits (photo d’ambiance)',
 chips=['Expresso & cappuccino', 'Crêpes', 'Glaces', 'Jus frais'],
 menu_h2='La carte du café', menu_lead='Produits relevés sur la fiche publique. Prix et carte complète à confirmer.',
 dishes=[dict(img='d1', alt='Tasse d’expresso', name='Expresso', desc='Le classique du matin.', tag='Carte en ligne'),
         dict(img='d2', alt='Cappuccino', name='Cappuccino', desc='Mousse de lait onctueuse.', tag='Carte en ligne'),
         dict(img='d3', alt='Crêpe au chocolat', name='Crêpes', desc='Sucrées, au choix.', tag='Carte en ligne'),
         dict(img='d4', alt='Jus de fruits', name='Jus & glaces', desc='Jus frais et coupes glacées.', tag='Carte en ligne')],
 menu_cats=['Cafés', 'Thés', 'Crêpes', 'Glaces', 'Jus', 'Omelettes'],
 slots=['08:00', '09:00', '10:00', '11:00', '12:00', '15:00', '16:00', '17:00', '18:00', '19:00', '20:00'],
 occ0='Café / goûter', msg_ph='Terrasse, groupe, anniversaire…',
 wa_msg='Bonjour Bridge Café, je souhaite réserver une table.',
 features=DEF_FEAT([('coffee', 'Commande à emporter', 'Commande envoyée sur WhatsApp, prête à votre arrivée.'), ('book', 'Menu QR', 'Carte et prix sur chaque table, modifiables en 1 minute.')]),
 gal_lead='Hammamet : médina, fort et plage, à quelques pas.',
 gallery=[('g1', 'Ruelle de la médina de Hammamet'), ('g2', 'Vue depuis le fort de Hammamet'), ('g3', 'Plage de Hammamet'), ('g4', 'Crêpe'), ('d2', 'Cappuccino'), ('d4', 'Jus de fruits')],
 wa='21697651544', wa_disp='+216 97 651 544', tels=['+216 97 651 544'],
 address='Avenue de la République, 8050 Hammamet', map_q='36.398477,10.615664', map_z=17,
 loc_h2='Avenue de la République', loc_p='En plein centre de Hammamet, à quelques minutes de la médina.',
 hours=[('Tous les jours', PH)], hours_short=f'Horaires {PH}',
 ratings=[rt('4.0', 1154, 'note moyenne', 'lacarte.menu', 'https://lacarte.menu/restaurants/hammamet/bridge-cafe-36')])

# 6 ------------------------------------------------------------------ HAPPY DAY (Nabeul)
resto(slug='happy-day-nabeul', name='Happy Day', mark='H', font='outfit',
 theme=dict(accent='#c2410c', accent2='#facc15', soft='#fdeadd', bg='#fffaf5', bgalt='#f8efe5', ink='#2a1206'),
 title='Happy Day — Restaurant & fast-food, avenue Habib Thameur, Nabeul (démo)',
 desc='Happy Day, Nabeul : kebab, panini, escalope, burger, pizza, pâtes et grillades, de 11h à minuit. Commande et réservation WhatsApp.',
 tagline='Restaurant & fast-food · Nabeul', eyebrow='Restaurant · av. Habib Thameur, Nabeul',
 h1='Bien manger à Nabeul, de midi à minuit',
 lead='Kebab, panini, escalope, burgers, pizzas et grillades : noté 4,4/5 par plus de 700 clients pour son rapport qualité-prix.',
 hero_alt='Sandwich panini (photo d’ambiance)',
 facts=[('11h – 00h', 'tous les jours'), ('Sur place', 'ou à emporter')],
 about_h2='Rapide, copieux, soigné',
 about_p=['Happy Day sert une cuisine généreuse à prix doux, sur place ou à emporter, en plein centre de Nabeul.',
          f'Cités sur la carte en ligne : kebab, panini, escalope panée, burger, pizza, pâtes, poisson, poulet, aloyau, salades et riz. Livraison {PH}.'],
 about_img='about', about_alt='Coucher de soleil à Nabeul (photo d’ambiance)',
 chips=['Kebab & panini', 'Escalope', 'Pizzas & burgers', 'Grillades'],
 menu_h2='Les favoris', menu_lead='Plats relevés sur la carte publique. Prix et formules à confirmer.',
 dishes=[dict(img='d1', alt='Sandwich kebab', name='Kebab', desc='Pain, viande grillée, crudités.', tag='Carte en ligne'),
         dict(img='d2', alt='Panini', name='Panini', desc='Chaud et croustillant.', tag='Carte en ligne'),
         dict(img='d3', alt='Pizza', name='Pizzas', desc='Au choix.', tag='Carte en ligne'),
         dict(img='d4', alt='Assiette de grillades', name='Aloyau & grillades', desc='Avec riz ou frites.', tag='Carte en ligne')],
 menu_cats=['Sandwichs', 'Paninis', 'Burgers', 'Pizzas', 'Pâtes', 'Assiettes grillées', 'Salades'],
 slots=['12:00', '12:30', '13:00', '13:30', '14:00', '19:00', '20:00', '21:00', '22:00', '23:00'],
 features=DEF_FEAT([('truck', 'À emporter', 'Commande pré-remplie sur WhatsApp, prête à votre arrivée.'), ('book', 'Menu QR', 'Prix et formules modifiables en 1 minute.')]),
 gal_lead='Nabeul, ville de la poterie et des souks.',
 gallery=[('g1', 'Souk de Nabeul'), ('g2', 'Centre-ville de Nabeul'), ('g3', 'Poteries de Nabeul'), ('hero', 'Panini'), ('d1', 'Kebab'), ('d3', 'Pizza')],
 wa='21620100792', wa_disp='+216 20 100 792', tels=['+216 20 100 792'],
 address='Avenue Habib Thameur, 8000 Nabeul', map_q='36.452523,10.731617', map_z=17,
 loc_h2='Au centre de Nabeul', loc_p='Avenue Habib Thameur, facile d’accès à pied ou en voiture.',
 hours=hrs_all('11:00 – 00:00'), hours_short='Tous les jours 11h – minuit',
 ratings=[rt('4.4', 714, 'note moyenne', 'lacarte.menu', 'https://lacarte.menu/restaurants/nabeul/happy-day-27')])

# 7 ------------------------------------------------------------------ L'EDEN (Mrezga)
resto(slug='leden-mrezga', name='L’Eden', mark='E', font='fraunces',
 theme=dict(accent='#166534', accent2='#f59e0b', soft='#e2f2e6', bg='#fafbf7', bgalt='#eef2e8', ink='#0f2415'),
 title='L’Eden — Café lounge vue mer, route touristique de Mrezga (démo)',
 desc='L’Eden, Mrezga : café lounge vue mer, citronnade, jus de fraise maison, crêpes, gaufres, de 8h à 2h. Réservation WhatsApp.',
 tagline='Café lounge · Mrezga', eyebrow='Café lounge · route touristique, Mrezga',
 h1='Citronnade, crêpes et vue sur la mer',
 lead='Un café lounge sur la route touristique de Mrezga : boissons fraîches maison, douceurs et soirées jusqu’à 2h du matin.',
 hero_alt='Terrasse illuminée sous les arbres le soir (photo d’ambiance)',
 facts=[('8h – 2h', 'tous les jours'), ('Vue mer', 'route touristique')],
 about_h2='Une pause fraîche entre Nabeul et Hammamet',
 about_p=['L’Eden accueille ses clients du café du matin jusqu’aux soirées d’été, avec la mer en toile de fond.',
          f'Cités en ligne : citronnade naturelle et aux amandes, jus de fraise maison, diabolo, lattés, crêpes, gaufres, glaces, croissants. Chicha {PH}.'],
 about_img='about', about_alt='Bord de mer à Mrezga (photo d’ambiance)',
 chips=['Vue mer', 'Jus frais maison', 'Crêpes & gaufres', 'Ouvert tard'],
 menu_h2='La carte de L’Eden', menu_lead='Produits relevés sur la carte publique. Prix à confirmer.',
 dishes=[dict(img='d1', alt='Tasse de café', name='Cafés & lattés', desc='Expresso, capucin, lattés.', tag='Carte en ligne'),
         dict(img='d2', alt='Jus de fraise', name='Jus de fraise maison', desc='Cité dans les avis clients.', tag='Avis clients'),
         dict(img='d3', alt='Crêpe', name='Crêpes & gaufres', desc='Chocolat, caramel, noisettes.', tag='Carte en ligne'),
         dict(img='d4', alt='Sandwich', name='Petite restauration', desc='Burgers, tacos au thon.', tag='Carte en ligne')],
 menu_cats=['Cafés', 'Jus frais', 'Citronnades', 'Diabolos', 'Crêpes & gaufres', 'Glaces', 'Petite restauration'],
 slots=['09:00', '11:00', '15:00', '17:00', '18:00', '19:00', '20:00', '21:00', '22:00', '23:00'],
 occ0='Café entre amis', msg_ph='Table vue mer, anniversaire…',
 features=DEF_FEAT([('waves', 'Vue mer', 'Tables en terrasse sur la route touristique.'), ('drop', 'Jus maison', 'Citronnade et jus de fraise préparés sur place.')]),
 gal_lead='Mrezga, entre plage et route touristique.',
 gallery=[('g1', 'Plage de Mrezga'), ('g2', 'Parasols de paille à Mrezga'), ('g3', 'Route touristique de Mrezga'), ('g4', 'Narguilés'), ('hero', 'Terrasse le soir'), ('d2', 'Jus de fraise')],
 wa='21698101242', wa_disp='+216 98 101 242', tels=['+216 98 101 242'],
 address='Route touristique, Mrezga (Nabeul)', map_q='36.422408,10.67351', map_z=17,
 loc_h2='Route touristique de Mrezga', loc_p='Entre Nabeul et Hammamet, côté mer.',
 hours=hrs_all('08:00 – 02:00'), hours_short='Tous les jours 8h – 2h',
 ratings=[rt('4.0', 136, 'note moyenne', 'lacarte.menu', 'https://lacarte.menu/restaurants/mrezga/leden-97')])

# 8 ------------------------------------------------------------------ CASA SUSHI (Hammamet Sud)
resto(slug='casa-sushi-hammamet', name='Casa Sushi', mark='S', font='jakarta', mode='order',
 theme=dict(accent='#b91c1c', accent2='#111827', soft='#fbe4e4', bg='#fcfaf8', bgalt='#f3eeea', ink='#1a0b0b'),
 title='Casa Sushi Hammamet — Sushis, livraison & à emporter (démo)',
 desc='Casa Sushi, Hammamet Sud : plateaux de sushis, makis, california, sashimis. Commande livraison ou à emporter via WhatsApp.',
 tagline='Sushi · livraison · Hammamet', eyebrow='Restaurant de sushis · Hammamet Sud',
 h1='Vos sushis à Hammamet, commandés en 1 minute',
 lead='Plateaux, makis, california et sashimis : commandez en livraison, à emporter ou sur place, directement sur WhatsApp.',
 hero_alt='Plateau de sushis (photo d’ambiance)',
 facts=[('12h – 00h', 'tous les jours'), ('Livraison', 'Hammamet & alentours')],
 about_h2='Le sushi, à Hammamet',
 about_p=['Casa Sushi se présente comme le premier restaurant de sushis de Hammamet : plateaux à partager, makis, california et sashimis.',
          f'Commande par téléphone ou WhatsApp, livraison ou à emporter. Zones et frais de livraison {PH}.'],
 about_img='about', about_alt='Coffret de sushis (photo d’ambiance)',
 chips=['Plateaux à partager', 'Makis', 'California', 'Livraison'],
 menu_h2='La carte sushi', menu_lead='Catégories d’exemple : pièces, compositions et prix à confirmer avec le restaurant.',
 dishes=[dict(img='d1', alt='Plateau saumon', name='Plateau 24 pièces', desc='À partager, assortiment du chef.', tag='Avis clients'),
         dict(img='d2', alt='Makis', name='Makis', desc='Saumon, thon, concombre…', tag='Exemple'),
         dict(img='d3', alt='Coffret de makis', name='California rolls', desc='Riz à l’extérieur, sésame.', tag='Exemple'),
         dict(img='d4', alt='Sashimis de saumon', name='Sashimis', desc='Tranches de poisson cru.', tag='Exemple')],
 menu_cats=['Plateaux', 'Makis', 'California', 'Sashimis', 'Nigiris', 'Soupes', 'Boissons'],
 order_ph='Ex. : plateau 24 pièces, 2 california saumon…',
 wa_msg='Bonjour Casa Sushi, je souhaite passer une commande.',
 form_intro='Bonjour Casa Sushi, je souhaite commander :',
 book_note=f'Prix, délai et frais de livraison confirmés par le restaurant. Zones de livraison {PH}.',
 features=DEF_FEAT([('truck', 'Livraison & à emporter', 'Commande pré-remplie, adresse incluse : moins d’erreurs, moins d’appels.'), ('book', 'Menu QR', 'Carte en photos, prix modifiables en 1 minute.')])[:3] + [('chat', 'Suivi de commande', 'Confirmation et heure de livraison envoyées sur WhatsApp.')],
 gal_lead='Des plateaux aux couleurs du Japon, à Hammamet.',
 gallery=[('g1', 'Assortiment de sushis'), ('g2', 'Coffret de sushis'), ('g3', 'Sushis'), ('g4', 'Yasmine Hammamet'), ('d1', 'Plateau saumon'), ('d2', 'Makis')],
 wa='21623333383', wa_disp='+216 23 333 383', tels=['+216 72 227 515', '+216 50 674 618'],
 address='Hammamet Sud, 8050 Hammamet', map_q='36.403448,10.569195', map_z=17,
 loc_h2='À Hammamet Sud', loc_p='Livraison sur Hammamet et environs, ou à emporter sur place.',
 hours=hrs_all('12:00 – 00:00'), hours_short='Tous les jours 12h – minuit',
 collect_txt='Un lien « Laissez un avis » dans le message de confirmation de commande : plus d’avis récents, moins de mauvaises surprises.',
 ratings=[rt('4.0', 370, 'note moyenne', 'lacarte.menu', 'https://lacarte.menu/restaurants/hammamet-sud/casa-sushi-hammamet')])

# 11 ----------------------------------------------------------------- ETTAHRIR (Hammamet)
resto(slug='ettahrir-hammamet', name='Restaurant Ettahrir', mark='ت', font='fraunces',
 theme=dict(accent='#a0522d', accent2='#2e7d6b', soft='#f5e6dc', bg='#fcf8f3', bgalt='#f3ebe1', ink='#27140a'),
 title='Restaurant Ettahrir (مطعم التحرير) — Cuisine tunisienne populaire, Hammamet (démo)',
 desc='Restaurant Ettahrir, avenue de la Libération, Hammamet : côtelettes, brick au thon, kemia, loubia, couscous, à petit prix. Réservation WhatsApp.',
 tagline='مطعم التحرير · Hammamet', eyebrow='Cuisine tunisienne · av. de la Libération, Hammamet',
 h1='La vraie cuisine tunisienne, à petit prix',
 lead='Côtelettes grillées, brick au thon, kemia offerte et couscous : l’adresse populaire de Hammamet, notée 4,4/5 sur Google par plus de 800 clients.',
 hero_alt='Médina de Hammamet (photo d’ambiance)',
 facts=[('12h – minuit', 'tous les jours'), ('~10–21 DT', f'par personne {PH}')],
 about_h2='Généreux, authentique, sans prétention',
 about_p=['Au centre de Hammamet, Ettahrir est réputé pour sa cuisine tunisienne simple et copieuse, servie en salle ou en terrasse.',
          f'Cités dans les avis : côtelettes d’agneau, merguez, brick au thon, kemia (petites entrées) offerte, loubia, poisson frit, couscous. Prix {PH}.'],
 about_img='about', about_alt='Repas tunisien avec entrées (photo d’ambiance)',
 chips=['Grillades', 'Kemia offerte', 'Couscous', 'Terrasse'],
 menu_h2='Les plats que les clients recommandent', menu_lead='Plats relevés dans les avis publics. Carte complète et prix à confirmer.',
 dishes=[dict(img='d1', alt='Côtelettes grillées', name='Côtelettes grillées', desc='Agneau grillé au charbon.', tag='Avis clients'),
         dict(img='d2', alt='Brick tunisienne', name='Brick au thon', desc='Croustillante, œuf coulant.', tag='Avis clients'),
         dict(img='d3', alt='Salade mechouia aux olives', name='Kemia', desc='Petites entrées offertes.', tag='Avis clients'),
         dict(img='d4', alt='Ojja merguez', name='Merguez & ojja', desc='Épicé, à la tunisienne.', tag='Exemple')],
 menu_cats=['Kemia & entrées', 'Bricks', 'Grillades', 'Poisson frit', 'Couscous', 'Loubia & plats du jour'],
 features=DEF_FEAT([('food', 'Plats du jour', 'Couscous et plats mijotés du jour affichés en ligne.'), ('book', 'Carte FR / AR / EN', 'Pour les habitués comme pour les touristes.')]),
 gal_lead='Hammamet, entre médina et remparts.',
 gallery=[('g1', 'Ruelle de la médina de Hammamet'), ('g2', 'Fort de Hammamet'), ('g3', 'Remparts de Hammamet'), ('g4', 'Couscous au poisson'), ('d1', 'Côtelettes grillées'), ('d2', 'Brick')],
 wa='21623196530', wa_disp='+216 23 196 530', tels=['+216 23 196 530'],
 address='Avenue de la Libération, 8050 Hammamet', map_q='36.4010317,10.6189723', map_z=17,
 loc_h2='Avenue de la Libération', loc_p='Au centre de Hammamet, à quelques minutes de la médina.',
 hours=hrs_all('12:00 – 00:00'), hours_short='Tous les jours 12h – minuit',
 ratings=[rt('4.4', 800, 'note Google (via Restaurant Guru)', 'restaurantguru.com', 'https://restaurantguru.com/Ettahrir-Hammamet'),
          rt('4.5', 276, 'note Tripadvisor (via Restaurant Guru)', 'restaurantguru.com', 'https://restaurantguru.com/Ettahrir-Hammamet'),
          rt('4.4', 51, 'note moyenne', 'plurielle.tn', 'https://plurielle.tn/pro/nabeul/%d9%85%d8%b7%d8%b9%d9%85-%d8%a7%d9%84%d8%aa%d8%ad%d8%b1%d9%8a%d8%b1-ettahrir-restaurant/')])

# 13 ----------------------------------------------------------------- HAOUARIA BEACH (El Haouaria)
resto(slug='haouaria-beach', name='Haouaria Beach', mark='H', font='outfit',
 theme=dict(accent='#0369a1', accent2='#f97316', soft='#e0f0fa', bg='#f9fbfc', bgalt='#ebf2f7', ink='#082033'),
 title='Haouaria Beach — Restaurant de plage, fruits de mer, El Haouaria (démo)',
 desc='Haouaria Beach, El Haouaria : paella, gratin de fruits de mer, seiches grillées, marmite de moules, loup grillé, sur la plage. Réservation WhatsApp.',
 tagline='Restaurant de plage · El Haouaria', eyebrow='Restaurant de plage · El Haouaria',
 h1='Paella et fruits de mer, les pieds dans le sable',
 lead='Paella pour deux, gratin de fruits de mer, seiches grillées et thé aux pignons, face à la mer d’El Haouaria.',
 hero_alt='Plage d’El Haouaria (photo d’ambiance)',
 facts=[('Plage', 'El Haouaria'), ('$$', 'budget moyen')],
 about_h2='La mer du Cap Bon, dans l’assiette',
 about_p=['Sur la plage d’El Haouaria, Haouaria Beach sert une cuisine de la mer simple et conviviale, à partager en famille ou entre amis.',
          f'Cités en ligne : paella (2 pers.), gratin de fruits de mer, seiches grillées, marmite de moules, loup grillé, thé aux pignons. Horaires et saison {PH}.'],
 about_img='about', about_alt='Plage d’El Haouaria (photo d’ambiance)',
 chips=['Paella', 'Fruits de mer', 'Sur la plage', 'Thé aux pignons'],
 menu_h2='Les plats de la mer', menu_lead='Plats relevés sur la fiche publique et les avis. Prix à confirmer.',
 dishes=[dict(img='d1', alt='Paella aux fruits de mer', name='Paella (2 pers.)', desc='À partager.', tag='Carte en ligne'),
         dict(img='d2', alt='Gratin', name='Gratin de fruits de mer', desc='Gratiné au four.', tag='Carte en ligne'),
         dict(img='d3', alt='Calamars grillés', name='Seiches grillées', desc='Selon arrivage.', tag='Carte en ligne'),
         dict(img='d4', alt='Poisson grillé', name='Loup grillé', desc='Au kilo, selon arrivage.', tag='Carte en ligne')],
 menu_cats=['Entrées', 'Paella', 'Gratins', 'Moules', 'Poisson grillé', 'Thé aux pignons'],
 features=DEF_FEAT([('waves', 'Sur la plage', f'Tables face à la mer ; saison et horaires {PH}.'), ('fire', 'Arrivage du jour', 'Poisson disponible affiché chaque jour.')]),
 gal_lead='El Haouaria : plages, criques et couchers de soleil sur Zembra.',
 gallery=[('g1', 'Plage d’El Haouaria'), ('g2', 'Plage d’El Haouaria'), ('g3', 'Coucher de soleil sur El Haouaria'), ('g4', 'Épave dans l’eau turquoise'), ('d1', 'Paella'), ('d2', 'Gratin')],
 wa='21654006083', wa_disp='+216 54 006 083', tels=['+216 54 006 083'],
 address='Plage d’El Haouaria, 8045 El Haouaria', map_q='Haouaria Beach, El Haouaria', map_z=16,
 map_note='Position approximative (plage d’El Haouaria) : emplacement exact à confirmer avec l’établissement.',
 loc_h2='Sur la plage d’El Haouaria', loc_p='À la pointe du Cap Bon, à environ 1h30 de Tunis.',
 hours=[('Tous les jours', PH)], hours_short=f'Horaires {PH}',
 ratings=[rt('3.7', 273, 'note moyenne', 'lacarte.menu', 'https://lacarte.menu/restaurants/el-haouaria/haouaria-beach')])

# 16 ----------------------------------------------------------------- RUSTIQUE INVITATION (Hammamet) — atelier faire-part
build_invit(dict(slug='rustique-invitation-hammamet', name='Rustique Invitation', mark='R', font='fraunces',
 theme=dict(accent='#7b5a3c', accent2='#b5838d', soft='#f4ebe3', bg='#fcfaf6', bgalt='#f3ede4', ink='#2a1d12'),
 title='Rustique Invitation — Faire-part & cartes d’invitation, Hammamet (démo)',
 desc='Rustique Invitation, Hammamet : faire-part de mariage, fiançailles, henna, naissance, sur mesure. Devis en 1 minute via WhatsApp.',
 tagline='Faire-part & invitations · Hammamet', eyebrow='Atelier de faire-part · Hammamet',
 h1='Des faire-part qui ressemblent à votre histoire',
 lead='Mariage, fiançailles, henna, naissance : des cartes d’invitation personnalisées, du style rustique kraft au plus élégant.',
 open_badge='Lun.–sam. 10h–20h · dim. 10h–13h', hero_alt='Faire-part (illustration)',
 about_eyebrow='L’atelier', about_h2='Un atelier d’invitations à Hammamet',
 about_p=['Rustique Invitation crée des cartes d’invitation et faire-part personnalisés pour les grands moments de la vie.',
          f'Modèles, papiers, finitions (dorure, sceau de cire, enveloppes) et délais de fabrication {PH} : ils seront présentés avec vos vraies réalisations.'],
 about_img='about', about_alt='Fleurs séchées (photo d’ambiance)',
 chips=['Mariage', 'Fiançailles', 'Henna', 'Naissance'],
 coll_h2='Trouvez votre style', coll_lead='Des catégories pour aider les futurs mariés à choisir avant même de vous appeler.',
 collections=[dict(img='c1', alt='Faire-part en papier kraft', name='Rustique kraft', desc='Papier kraft, ficelle, étiquettes.'),
              dict(img='c2', alt='Calligraphie à la plume', name='Calligraphie', desc='Textes en arabe et en français.'),
              dict(img='c3', alt='Henné sur une main', name='Henna & outya', desc='Cartes pour les fêtes traditionnelles.'),
              dict(img='c4', alt='Faire-part moderne', name='Moderne & minimal', desc='Lignes épurées, typographies fines.'),
              dict(img='c5', alt='Fleurs séchées', name='Bohème fleurs séchées', desc='Fleurs séchées et tons naturels.'),
              dict(img='c6', alt='Table de réception', name='Papeterie de table', desc='Menus, marque-places, plans de table.')],
 features=[('chat', '1. Votre idée', 'Envoyez une photo d’inspiration et vos couleurs sur WhatsApp.'), ('book', '2. Maquette & BAT', 'Bon à tirer validé en ligne, prénoms et dates vérifiés.'),
           ('store', '3. Fabrication', f'Impression et finitions à l’atelier, délai {PH}.'), ('truck', '4. Retrait ou livraison', f'À l’atelier de Hammamet ou livraison {PH}.')],
 gal_h2='Inspirations', gal_lead='Couleurs, matières et détails pour vos invitations.',
 gallery=[('g1', 'Bouquet de mariée'), ('g2', 'Fleurs séchées'), ('g3', 'Calligraphie sur bois'), ('g4', 'Table de réception décorée'), ('c1', 'Faire-part kraft'), ('c2', 'Calligraphie')],
 book_note=f'Prix par quantité, délais et minimum de commande {PH}.',
 form_intro='Bonjour Rustique Invitation, je souhaite un devis :',
 wa_msg='Bonjour Rustique Invitation, je souhaite un devis pour des faire-part.',
 wa='21656169266', wa_disp='+216 56 169 266', tels=['+216 56 169 266'], email='',
 address='Rue Hassan Hosni Abdelwahab, 8050 Hammamet', map_q='36.4032338,10.6378607', map_z=17,
 loc_h2='L’atelier à Hammamet', loc_p='Venez voir et toucher les modèles à l’atelier.',
 hours=[('Lundi – Samedi', '10:00 – 20:00'), ('Dimanche', '10:00 – 13:00')], hours_short='Lun.–sam. 10h–20h · dim. 10h–13h',
 social=[('Facebook', 'www.facebook.com/rustiqueinvitation')],
 collect_txt='Un lien « Laissez un avis » envoyé avec la livraison des cartes : vos clients satisfaits deviennent votre vitrine.',
 ratings=[rt('5.0', 69, 'note moyenne', 'plurielle.tn', 'https://plurielle.tn/pro/nabeul/rustique-invitation/')]))
