# Lot 1 (Cap Bon) — maisons d'hôtes / locations, FR/EN/IT, via gen_guest.build (même design que lot 0).
import sys, os; sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from gen_guest import build
from urllib.parse import quote

PH3 = ('<span class="ph">à confirmer</span>', '<span class="ph">to be confirmed</span>', '<span class="ph">da confermare</span>')
def tr(fr, en, it): return (fr, en, it)
def ratings_block(S, items):
    """items: list of (score, count, src, url). Public ratings only, with source (i18n)."""
    cards = ''
    for i, (sc, n, src, url) in enumerate(items):
        pct = float(sc) / 5 * 100
        cards += (f'<div class="rating reveal"><div class="score">{sc}<small> / 5</small></div><span class="stars" aria-label="{sc}/5">★★★★★<i style="width:{pct:.0f}%">★★★★★</i></span>'
                  f'<p><b>{n}</b> <span data-i18n="rv_n">avis</span></p><a href="{url}" target="_blank" rel="noopener"><span data-i18n="rv_src">Source :</span> {src} →</a><p><span data-i18n="rv_date">Relevé le</span> 30/09/2026</p></div>')
    cards += ('<div class="rating reveal" style="background:var(--accent-soft)"><h3 style="margin:0;font-size:1.1rem" data-i18n="rv_ct">Collecte d\'avis</h3>'
              '<p style="color:var(--ink)" data-i18n="rv_cd">Un message WhatsApp de remerciement après le séjour, avec lien « Laissez un avis » : plus d\'avis récents.</p><span class="ph" data-i18n="rv_mod">module Synaris, démo</span></div>')
    S['t'].update({
        'rv_e': tr('Avis voyageurs', 'Guest reviews', 'Recensioni'), 'rv_h': tr('Leur note en ligne', 'Their online rating', 'Il loro voto online'),
        'rv_l': tr("Notes publiques uniquement, avec leur source. Aucun avis n'a été inventé ni copié.", 'Public ratings only, with their source. No review was invented or copied.', 'Solo voti pubblici, con la fonte. Nessuna recensione inventata o copiata.'),
        'rv_n': tr('avis', 'reviews', 'recensioni'), 'rv_src': tr('Source :', 'Source:', 'Fonte:'), 'rv_date': tr('Relevé le', 'Checked on', 'Rilevato il'),
        'rv_ct': tr("Collecte d'avis", 'Review collection', 'Raccolta recensioni'),
        'rv_cd': tr("Un message WhatsApp de remerciement après le séjour, avec lien « Laissez un avis » : plus d'avis récents.", 'A WhatsApp thank-you message after the stay, with a “Leave a review” link: more recent reviews.', 'Un messaggio WhatsApp di ringraziamento dopo il soggiorno, con link “Lascia una recensione”: più recensioni recenti.'),
        'rv_mod': tr('module Synaris, démo', 'Synaris module, demo', 'modulo Synaris, demo'),
    })
    return ('<section class="section" id="avis"><div class="container"><div class="center"><span class="eyebrow" data-i18n="rv_e">Avis voyageurs</span><h2 data-i18n="rv_h">Leur note en ligne</h2>'
            f'<p class="lead" data-i18n="rv_l">{S["t"]["rv_l"][0]}</p></div><div class="ratings">{cards}</div></div></section>')

def base_t(tagline, extra):
    t = {'tagline': tagline, 'loc_btn': tr('Itinéraire Google Maps', 'Directions on Google Maps', 'Indicazioni su Google Maps'),
         'feat_eyebrow': tr('Services', 'Services', 'Servizi')}
    t.update(extra); return t

# ================================================================= LA MAISON DU GOLFE (Hammamet Nord)
golfe = dict(slug='maison-du-golfe-hammamet', name='La Maison du Golfe', mark='G', font='playfair',
 title="La Maison du Golfe — Maison d'hôtes & spa, Hammamet Nord (démo)",
 desc="La Maison du Golfe, Hammamet : 6 suites et chambres, spa (hammam, sauna, jacuzzi), piscine, 7 000 m² de vergers et d'oliviers. Réservation directe.",
 theme=dict(accent='#2f5d50', accent2='#d9a441', soft='#e3efe9', bg='#fbfaf5', bgalt='#f0eee4', ink='#12231d'),
 wa='21692005177', tel='+21692005177', tel_disp='+216 92 005 177', wa_disp='+216 92 005 177',
 wa_text=quote("Bonjour La Maison du Golfe, je souhaite des informations pour un séjour."),
 fb='www.facebook.com/lamaisondugolfe.tn', fb_disp='Page Facebook La Maison du Golfe',
 address="Route de la Faouara, Bir Bou Rekba, Hammamet Nord",
 map_q=quote('36.4266767,10.5978732'),
 hero_alt="Terrasse et piscine d'une maison d'hôtes (photo d'ambiance)", about_img='about', about_alt="Oliveraie du Cap Bon (photo d'ambiance)",
 facts=['fa', 'fb', 'fc', 'fd'], max_guests=6, spaces=['sp1', 'sp2', 'sp3', 'sp4'],
 rooms=[dict(k='r1', img='room1', alt="Suite d'inspiration tunisienne (ambiance)", price='—', tags=['tg_view', 'tg_ac', 'tg_bath']),
        dict(k='r2', img='room2', alt='Suite lumineuse (ambiance)', price='—', tags=['tg_garden', 'tg_ac', 'tg_bath']),
        dict(k='r3', img='room3', alt='Chambre double (ambiance)', price='—', tags=['tg_ac', 'tg_bath', 'tg_2'])],
 extra_opts=['Suite junior'], rooms_cols='c3',
 features=[('coffee', 'ft1'), ('drop', 'ft2'), ('waves', 'ft3'), ('food', 'ft4'), ('home', 'ft5'), ('car', 'ft6'), ('wifi', 'ft7'), ('map', 'ft8')],
 gallery=[('pool', 'Piscine (ambiance)'), ('spa', 'Hammam traditionnel (ambiance)'), ('g1', 'Plage de Hammamet'), ('g2', 'La mer vue du fort de Hammamet'), ('g3', 'Couscous tunisien'), ('g4', 'Oliveraie'), ('room1', 'Suite'), ('hero', 'Terrasse'), ('about', 'Oliviers du Cap Bon')],
 t=base_t(tr("Maison d'hôtes & spa · Hammamet", 'Guesthouse & spa · Hammamet', 'Casa vacanze & spa · Hammamet'), {
  'nav_rooms': tr('Suites', 'Suites', 'Suite'),
  'hero_eyebrow': tr("Maison d'hôtes & spa · Hammamet Nord", 'Guesthouse & spa · Hammamet North', 'Casa vacanze & spa · Hammamet Nord'),
  'hero_h1': tr('Le calme des vergers, à deux pas du golfe de Hammamet', 'Orchard calm, a stone’s throw from the Gulf of Hammamet', 'La quiete dei frutteti, a due passi dal golfo di Hammamet'),
  'hero_lead': tr("Six suites et chambres sur 7 000 m² d'orangers et d'oliviers, un spa avec hammam, sauna et jacuzzi, et une table du terroir tunisien.",
                  'Six suites and rooms on 7,000 m² of orange and olive trees, a spa with hammam, sauna and jacuzzi, and Tunisian farm-to-table cooking.',
                  'Sei suite e camere su 7.000 m² di aranci e ulivi, una spa con hammam, sauna e jacuzzi, e una cucina tunisina del territorio.'),
  'fa_b': tr('6 hébergements', '6 units', '6 alloggi'), 'fa_s': tr('4 suites · 1 junior · 1 chambre', '4 suites · 1 junior · 1 room', '4 suite · 1 junior · 1 camera'),
  'fb_b': tr('Spa', 'Spa', 'Spa'), 'fb_s': tr('hammam · sauna · jacuzzi', 'hammam · sauna · jacuzzi', 'hammam · sauna · jacuzzi'),
  'fc_b': tr('7 000 m²', '7,000 m²', '7.000 m²'), 'fc_s': tr('de vergers et oliviers', 'of orchards and olives', 'di frutteti e ulivi'),
  'fd_b': tr('Piscine', 'Pool', 'Piscina'), 'fd_s': tr('extérieure, juin → oct.', 'outdoor, June → Oct.', 'esterna, giugno → ott.'),
  'about_eyebrow': tr('La maison', 'The house', 'La casa'),
  'about_h2': tr("Une maison de famille au milieu des vergers", 'A family house among the orchards', 'Una casa di famiglia tra i frutteti'),
  'about_p1': tr("Ouverte en 2018 par Aziz et Leila, La Maison du Golfe accueille ses hôtes sur un domaine de 7 000 m² planté d'arbres fruitiers et d'oliviers, sur la route de la Faouara.",
                 'Opened in 2018 by Aziz and Leila, La Maison du Golfe welcomes guests on a 7,000 m² estate planted with fruit and olive trees, on the Faouara road.',
                 "Aperta nel 2018 da Aziz e Leila, La Maison du Golfe accoglie gli ospiti in una tenuta di 7.000 m² con alberi da frutto e ulivi, sulla strada della Faouara."),
  'about_p2': tr("Spa avec hammam, sauna, piscine intérieure avec jacuzzi et salles de massage, piscine extérieure en saison, aire de jeux pour les enfants et cuisine partagée : un cadre pensé pour les familles comme pour les couples.",
                 'Spa with hammam, sauna, indoor pool with jacuzzi and massage rooms, a seasonal outdoor pool, a kids’ playground and a shared kitchen: designed for families and couples alike.',
                 'Spa con hammam, sauna, piscina interna con jacuzzi e sale massaggi, piscina esterna stagionale, area giochi per bambini e cucina condivisa: pensata per famiglie e coppie.'),
  'sp1': tr('Spa & hammam', 'Spa & hammam', 'Spa & hammam'), 'sp2': tr('Piscine intérieure', 'Indoor pool', 'Piscina interna'), 'sp3': tr('Aire de jeux', 'Playground', 'Area giochi'), 'sp4': tr('Cuisine partagée', 'Shared kitchen', 'Cucina condivisa'),
  'rooms_eyebrow': tr('Suites & chambre', 'Suites & room', 'Suite & camera'),
  'rooms_h2': tr('Six hébergements, dont une suite vue sur le golfe', 'Six units, including a suite overlooking the gulf', 'Sei alloggi, tra cui una suite vista golfo'),
  'rooms_lead': tr('4 suites, 1 suite junior et 1 chambre. Petit-déjeuner servi de 7h30 à 9h30. Tarifs par nuit à confirmer.',
                   '4 suites, 1 junior suite and 1 room. Breakfast served 7:30–9:30 am. Nightly rates to be confirmed.',
                   '4 suite, 1 junior suite e 1 camera. Colazione dalle 7:30 alle 9:30. Tariffe a notte da confermare.'),
  'r1_n': tr('Suite vue sur le golfe', 'Gulf-view suite', 'Suite vista golfo'), 'r1_d': tr("À l'étage, avec vue sur le golfe de Hammamet.", 'Upstairs, overlooking the Gulf of Hammamet.', 'Al piano superiore, con vista sul golfo di Hammamet.'),
  'r2_n': tr('Suites jardin', 'Garden suites', 'Suite giardino'), 'r2_d': tr('Spacieuses, ouvertes sur les vergers.', 'Spacious, opening onto the orchards.', 'Spaziose, aperte sui frutteti.'),
  'r3_n': tr('Suite junior & chambre', 'Junior suite & room', 'Junior suite & camera'), 'r3_d': tr('Pour un couple ou un court séjour.', 'For a couple or a short stay.', 'Per una coppia o un breve soggiorno.'),
  'tg_view': tr('Vue golfe', 'Gulf view', 'Vista golfo'), 'tg_garden': tr('Jardin', 'Garden', 'Giardino'), 'tg_ac': tr('Climatisation', 'Air-con', 'Aria condizionata') , 'tg_bath': tr('Salle de bain', 'Bathroom', 'Bagno'), 'tg_2': tr('2 personnes', '2 guests', '2 ospiti'),
  'feat_h2': tr('Tout pour se ressourcer', 'Everything to recharge', 'Tutto per rigenerarsi'),
  'ft1_t': tr('Petit-déjeuner', 'Breakfast', 'Colazione'), 'ft1_d': tr('Servi de 7h30 à 9h30.', 'Served 7:30–9:30 am.', 'Servita dalle 7:30 alle 9:30.'),
  'ft2_t': tr('Spa offert', 'Free spa', 'Spa gratuita'), 'ft2_d': tr('Hammam, sauna, jacuzzi pour les hôtes.', 'Hammam, sauna, jacuzzi for guests.', 'Hammam, sauna, jacuzzi per gli ospiti.'),
  'ft3_t': tr('Piscine extérieure', 'Outdoor pool', 'Piscina esterna'), 'ft3_d': tr('De juin à octobre.', 'June to October.', 'Da giugno a ottobre.'),
  'ft4_t': tr('Table du terroir', 'Local cuisine', 'Cucina del territorio'), 'ft4_d': tr('Menus tunisiens sur réservation ' + PH3[0], 'Tunisian menus on request ' + PH3[1], 'Menu tunisini su prenotazione ' + PH3[2]),
  'ft5_t': tr('Enfants bienvenus', 'Kids welcome', 'Bambini benvenuti'), 'ft5_d': tr('Aire de jeux dans le jardin.', 'Playground in the garden.', 'Area giochi in giardino.'),
  'ft6_t': tr('Parking gratuit', 'Free parking', 'Parcheggio gratuito'), 'ft6_d': tr('Sur place.', 'On site.', 'In loco.'),
  'ft7_t': tr('Wi-Fi', 'Wi-Fi', 'Wi-Fi'), 'ft7_d': tr('Gratuit.', 'Free.', 'Gratuito.'),
  'ft8_t': tr('Hammamet', 'Hammamet', 'Hammamet'), 'ft8_d': tr('Plages, médina et Yasmine à proximité.', 'Beaches, medina and Yasmine nearby.', 'Spiagge, medina e Yasmine vicine.'),
  'gal_h2': tr('Le domaine et Hammamet', 'The estate and Hammamet', 'La tenuta e Hammamet'),
  'gal_lead': tr('Spa, piscine, vergers et la mer toute proche. <span class="ph">Photos d’ambiance — à remplacer par vos photos</span>', 'Spa, pool, orchards and the sea nearby. <span class="ph">Mood photos — to be replaced with yours</span>', 'Spa, piscina, frutteti e il mare vicino. <span class="ph">Foto d’atmosfera — da sostituire</span>'),
  'book_extra': tr('Horaires d’arrivée et de départ ' + PH3[0] + '<br>Assistant WhatsApp FR/EN/IT 24h/24 activable : réponses automatiques (prix, disponibilités, spa, accès).',
                   'Check-in/check-out times ' + PH3[1] + '<br>Optional 24/7 FR/EN/IT WhatsApp assistant: instant answers (rates, availability, spa, directions).',
                   'Orari di arrivo/partenza ' + PH3[2] + '<br>Assistente WhatsApp FR/EN/IT 24/7 attivabile: risposte automatiche (tariffe, disponibilità, spa, accesso).'),
  'loc_h2': tr('Route de la Faouara, Hammamet Nord', 'Faouara road, Hammamet North', 'Strada della Faouara, Hammamet Nord'),
  'loc_p': tr('À Bir Bou Rekba, entre vergers et oliviers, à quelques minutes des plages de Hammamet. Environ 1h de Tunis-Carthage.',
              'In Bir Bou Rekba, among orchards and olive trees, minutes from Hammamet’s beaches. About 1 hour from Tunis-Carthage.',
              'A Bir Bou Rekba, tra frutteti e ulivi, a pochi minuti dalle spiagge di Hammamet. Circa 1 ora da Tunisi-Cartagine.'),
 }))
golfe['extra_section'] = ratings_block(golfe, [('4.5', 54, 'plurielle.tn', 'https://plurielle.tn/pro/nabeul/la-maison-du-golfe-hammamet/')])

# ================================================================= DAR CLAUDINE (Bir Bou Rekba, Hammamet)
claud = dict(slug='dar-claudine-hammamet', name='Dar Claudine', mark='C', font='dmserif',
 title="Dar Claudine — Maison d'hôtes à Bir Bou Rekba, Hammamet (démo)",
 desc="Dar Claudine, maison d'hôtes à Bir Bou Rekba (Hammamet), notée 5/5 en ligne. Chambres, services et réservation directe sur WhatsApp.",
 theme=dict(accent='#2b5f8a', accent2='#e8b04b', soft='#e2edf6', bg='#fbfaf7', bgalt='#eff1ee', ink='#10202e'),
 wa='21622788362', tel='+21622788362', tel_disp='+216 22 788 362', wa_disp='+216 22 788 362',
 wa_text=quote("Bonjour Dar Claudine, je souhaite des informations pour un séjour."),
 fb='', address="Bir Bou Rekba, Hammamet (adresse exacte à confirmer)",
 map_q=quote('36.4107749,10.5726964'),
 hero_alt="Terrasse blanche et bleue de style tunisien (photo d'ambiance)", about_img='about', about_alt="Porte bleue tunisienne (photo d'ambiance)",
 facts=['fa', 'fb', 'fc', 'fd'], max_guests=6, spaces=['sp1', 'sp2', 'sp3'],
 rooms=[dict(k='r1', img='room1', alt='Chambre double (ambiance)', price='—', tags=['tg_2', 'tg_ac']),
        dict(k='r2', img='room2', alt='Chambre de style tunisien (ambiance)', price='—', tags=['tg_fam', 'tg_ac']),
        dict(k='r3', img='patio', alt='Patio (ambiance)', price='—', tags=['tg_patio'])],
 rooms_cols='c3',
 features=[('coffee', 'ft1'), ('wifi', 'ft2'), ('car', 'ft3'), ('map', 'ft4')],
 gallery=[('hero', 'Terrasse de style tunisien'), ('g1', 'Plage de Hammamet'), ('g2', 'Médina de Hammamet'), ('g3', 'Oliveraie du Cap Bon'), ('g4', 'Remparts de Hammamet')],
 t=base_t(tr("Maison d'hôtes · Hammamet", 'Guesthouse · Hammamet', 'Casa vacanze · Hammamet'), {
  'nav_rooms': tr('Chambres', 'Rooms', 'Camere'),
  'hero_eyebrow': tr("Maison d'hôtes · Bir Bou Rekba, Hammamet", 'Guesthouse · Bir Bou Rekba, Hammamet', 'Casa vacanze · Bir Bou Rekba, Hammamet'),
  'hero_h1': tr('Une maison d’hôtes notée 5/5, au calme près de Hammamet', 'A 5/5-rated guesthouse, in a quiet spot near Hammamet', 'Una casa vacanze valutata 5/5, nella quiete vicino a Hammamet'),
  'hero_lead': tr("Dar Claudine accueille ses hôtes à Bir Bou Rekba, entre campagne et plages de Hammamet. Réservez en direct, sans intermédiaire.",
                  'Dar Claudine welcomes guests in Bir Bou Rekba, between countryside and Hammamet’s beaches. Book direct, no middleman.',
                  'Dar Claudine accoglie gli ospiti a Bir Bou Rekba, tra campagna e spiagge di Hammamet. Prenota direttamente, senza intermediari.'),
  'fa_b': tr('5,0 / 5', '5.0 / 5', '5,0 / 5'), 'fa_s': tr('59 avis en ligne', '59 online reviews', '59 recensioni online'),
  'fb_b': tr('Bir Bou Rekba', 'Bir Bou Rekba', 'Bir Bou Rekba'), 'fb_s': tr('Hammamet', 'Hammamet', 'Hammamet'),
  'fc_b': tr('Direct', 'Direct', 'Diretto'), 'fc_s': tr('réservation WhatsApp', 'WhatsApp booking', 'prenotazione WhatsApp'),
  'fd_b': tr('FR · EN · IT', 'FR · EN · IT', 'FR · EN · IT'), 'fd_s': tr('accueil multilingue', 'multilingual welcome', 'accoglienza multilingue'),
  'about_eyebrow': tr('La maison', 'The house', 'La casa'),
  'about_h2': tr('Une adresse confidentielle, plébiscitée par ses hôtes', 'A hidden gem, loved by its guests', 'Un indirizzo riservato, amato dai suoi ospiti'),
  'about_p1': tr("Dar Claudine est une maison d'hôtes de Bir Bou Rekba, à quelques minutes de Hammamet, dont les voyageurs saluent l'accueil (note 5/5 en ligne).",
                 'Dar Claudine is a guesthouse in Bir Bou Rekba, minutes from Hammamet, whose guests praise the welcome (5/5 online rating).',
                 "Dar Claudine è una casa vacanze a Bir Bou Rekba, a pochi minuti da Hammamet, i cui ospiti lodano l'accoglienza (voto 5/5 online)."),
  'about_p2': tr("Chambres, équipements, tarifs et services " + PH3[0] + " : cette démo sera complétée avec vos informations et vos photos.",
                 'Rooms, amenities, rates and services ' + PH3[1] + ': this demo will be completed with your information and photos.',
                 'Camere, servizi, tariffe ' + PH3[2] + ': questa demo sarà completata con le vostre informazioni e foto.'),
  'sp1': tr('Chambres', 'Rooms', 'Camere'), 'sp2': tr('Espaces communs', 'Shared spaces', 'Spazi comuni'), 'sp3': tr('Jardin / terrasse ' + PH3[0], 'Garden / terrace ' + PH3[1], 'Giardino / terrazza ' + PH3[2]),
  'rooms_eyebrow': tr('Chambres', 'Rooms', 'Camere'),
  'rooms_h2': tr('Les chambres', 'The rooms', 'Le camere'),
  'rooms_lead': tr('Types de chambres donnés à titre d’exemple : nombre, équipements et tarifs à confirmer.', 'Room types shown as examples: number, amenities and rates to be confirmed.', 'Tipi di camere a titolo di esempio: numero, servizi e tariffe da confermare.'),
  'r1_n': tr('Chambre double', 'Double room', 'Camera doppia'), 'r1_d': tr('Pour deux personnes.', 'For two guests.', 'Per due persone.'),
  'r2_n': tr('Chambre familiale', 'Family room', 'Camera familiare'), 'r2_d': tr('Pour les familles.', 'For families.', 'Per famiglie.'),
  'r3_n': tr('Espaces communs', 'Shared spaces', 'Spazi comuni'), 'r3_d': tr('Patio, salon, terrasse.', 'Patio, lounge, terrace.', 'Patio, salotto, terrazza.'),
  'tg_2': tr('2 personnes', '2 guests', '2 ospiti'), 'tg_fam': tr('Familles', 'Families', 'Famiglie'), 'tg_ac': tr('Climatisation ' + PH3[0], 'Air-con ' + PH3[1], 'Aria condizionata ' + PH3[2]), 'tg_patio': tr('Patio', 'Patio', 'Patio'),
  'feat_h2': tr('Un séjour simple et chaleureux', 'A simple, warm stay', 'Un soggiorno semplice e accogliente'),
  'ft1_t': tr('Petit-déjeuner', 'Breakfast', 'Colazione'), 'ft1_d': PH3,
  'ft2_t': tr('Wi-Fi', 'Wi-Fi', 'Wi-Fi'), 'ft2_d': PH3,
  'ft3_t': tr('Parking', 'Parking', 'Parcheggio'), 'ft3_d': PH3,
  'ft4_t': tr('Hammamet', 'Hammamet', 'Hammamet'), 'ft4_d': tr('Plages et médina à proximité.', 'Beaches and medina nearby.', 'Spiagge e medina vicine.'),
  'gal_h2': tr('Hammamet et ses environs', 'Hammamet and around', 'Hammamet e dintorni'),
  'gal_lead': tr('Plages, médina et campagne du Cap Bon. <span class="ph">Photos d’ambiance — à remplacer par vos photos</span>', 'Beaches, medina and Cap Bon countryside. <span class="ph">Mood photos — to be replaced with yours</span>', 'Spiagge, medina e campagna di Cap Bon. <span class="ph">Foto d’atmosfera — da sostituire</span>'),
  'book_extra': tr('Assistant WhatsApp FR/EN/IT 24h/24 activable : réponses automatiques aux questions fréquentes.', 'Optional 24/7 FR/EN/IT WhatsApp assistant: instant answers to FAQs.', 'Assistente WhatsApp FR/EN/IT 24/7 attivabile: risposte automatiche alle domande frequenti.'),
  'loc_h2': tr('À Bir Bou Rekba', 'In Bir Bou Rekba', 'A Bir Bou Rekba'),
  'loc_p': tr('Entre Hammamet et la campagne du Cap Bon. Adresse exacte communiquée à la réservation.', 'Between Hammamet and the Cap Bon countryside. Exact address given on booking.', 'Tra Hammamet e la campagna di Cap Bon. Indirizzo esatto comunicato alla prenotazione.'),
 }))
claud['extra_section'] = ratings_block(claud, [('5.0', 59, 'plurielle.tn', 'https://plurielle.tn/pro/nabeul/dar-claudine/')])

# ================================================================= APPARTEMENTS MANSOUR (Kélibia)
mans = dict(slug='appartements-mansour-kelibia', name='Appartements Mansour', mark='M', font='outfit',
 title="Appartements Mansour — Appartement S+3 à louer à Kélibia (démo)",
 desc="Appartement S+3 à louer à Kélibia, près de Mansoura : 3 chambres, séjour, cuisine. Réservation directe sur WhatsApp.",
 theme=dict(accent='#0f766e', accent2='#f59e0b', soft='#dcf2ef', bg='#f9fbfa', bgalt='#ebf2f0', ink='#0a201d'),
 wa='21620318607', tel='+21620318607', tel_disp='+216 20 318 607', wa_disp='+216 20 318 607',
 wa_text=quote("Bonjour, je souhaite des informations sur l'appartement S+3 à Kélibia."),
 fb='www.facebook.com/mansourappartkelibia', fb_disp='Page Facebook Appartements Mansour',
 address="Kélibia, côté Mansoura (adresse exacte à confirmer)",
 map_q=quote('36.8478519,11.1234388'),
 hero_alt="Plage de Mansoura à Kélibia (photo d'ambiance)", about_img='about', about_alt="Séjour d'appartement (photo d'ambiance)",
 facts=['fa', 'fb', 'fc', 'fd'], max_guests=8, spaces=['sp1', 'sp2', 'sp3', 'sp4'],
 rooms=[dict(k='r1', img='room1', alt='Chambre (ambiance)', price='—', tags=['tg_bed']),
        dict(k='r2', img='room2', alt='Chambre (ambiance)', price='—', tags=['tg_bed']),
        dict(k='r3', img='living', alt='Séjour (ambiance)', price='—', tags=['tg_salon']),
        dict(k='r4', img='kitchen', alt='Cuisine (ambiance)', price='—', tags=['tg_kitchen'])],
 rooms_cols='c4',
 features=[('key', 'ft1'), ('home', 'ft2'), ('waves', 'ft3'), ('car', 'ft4'), ('snow', 'ft5'), ('wifi', 'ft6'), ('calendar', 'ft7'), ('map', 'ft8')],
 gallery=[('g1', 'Plage de Kélibia'), ('g2', 'Plage de Kélibia'), ('g3', 'Promenade à Sidi Mansour'), ('g4', 'Fort de Kélibia'), ('hero', 'Plage de Mansoura')],
 t=base_t(tr('Location S+3 · Kélibia', 'S+3 rental · Kélibia', 'Affitto S+3 · Kélibia'), {
  'nav_rooms': tr("L'appartement", 'The apartment', "L'appartamento"),
  'hero_eyebrow': tr('Location de vacances · Kélibia, Cap Bon', 'Holiday rental · Kélibia, Cap Bon', 'Affitto vacanze · Kélibia, Cap Bon'),
  'hero_h1': tr('Un grand appartement S+3 pour vos vacances à Kélibia', 'A spacious 3-bedroom apartment for your Kélibia holiday', 'Un ampio trilocale S+3 per le vacanze a Kélibia'),
  'hero_lead': tr('Trois chambres, un séjour et une cuisine, près des plages de Mansoura et de Kélibia. Vérifiez les dates et réservez en direct.',
                  'Three bedrooms, a living room and a kitchen, near the beaches of Mansoura and Kélibia. Check dates and book direct.',
                  'Tre camere, soggiorno e cucina, vicino alle spiagge di Mansoura e Kélibia. Verifica le date e prenota direttamente.'),
  'fa_b': tr('S+3', 'S+3', 'S+3'), 'fa_s': tr('3 chambres + séjour', '3 bedrooms + living', '3 camere + soggiorno'),
  'fb_b': tr('Mansoura', 'Mansoura', 'Mansoura'), 'fb_s': tr('Kélibia', 'Kélibia', 'Kélibia'),
  'fc_b': tr('4,3 / 5', '4.3 / 5', '4,3 / 5'), 'fc_s': tr('52 avis en ligne', '52 online reviews', '52 recensioni online'),
  'fd_b': tr('Familles', 'Families', 'Famiglie'), 'fd_s': tr('jusqu’à 8 pers. ' + PH3[0], 'up to 8 guests ' + PH3[1], 'fino a 8 persone ' + PH3[2]),
  'about_eyebrow': tr("L'appartement", 'The apartment', "L'appartamento"),
  'about_h2': tr('De la place pour toute la famille', 'Room for the whole family', 'Spazio per tutta la famiglia'),
  'about_p1': tr("Un appartement S+3 à louer à Kélibia, du côté de Mansoura : idéal pour les familles et les groupes d'amis qui veulent profiter des plages du Cap Bon.",
                 'A 3-bedroom (S+3) apartment for rent in Kélibia, on the Mansoura side: ideal for families and groups of friends enjoying Cap Bon’s beaches.',
                 'Un appartamento S+3 in affitto a Kélibia, lato Mansoura: ideale per famiglie e gruppi di amici che vogliono godersi le spiagge di Cap Bon.'),
  'about_p2': tr('Surface, étage, équipements (climatisation, Wi-Fi, parking, linge), distance à la plage et tarifs par nuit ou par semaine ' + PH3[0] + '.',
                 'Size, floor, amenities (air-con, Wi-Fi, parking, linen), distance to the beach and nightly/weekly rates ' + PH3[1] + '.',
                 'Superficie, piano, servizi (aria condizionata, Wi-Fi, parcheggio, biancheria), distanza dalla spiaggia e tariffe ' + PH3[2] + '.'),
  'sp1': tr('3 chambres', '3 bedrooms', '3 camere'), 'sp2': tr('Séjour', 'Living room', 'Soggiorno'), 'sp3': tr('Cuisine', 'Kitchen', 'Cucina'), 'sp4': tr('Proche plages', 'Near beaches', 'Vicino alle spiagge'),
  'rooms_eyebrow': tr("L'appartement", 'The apartment', "L'appartamento"),
  'rooms_h2': tr('Pièce par pièce', 'Room by room', 'Stanza per stanza'),
  'rooms_lead': tr('Photos d’ambiance : vos vraies photos seront ajoutées. Tarif par nuit / semaine à confirmer (haute et basse saison).',
                   'Mood photos: your real photos will be added. Nightly / weekly rate to be confirmed (high and low season).',
                   'Foto d’atmosfera: verranno aggiunte le vostre foto reali. Tariffa a notte / settimana da confermare (alta e bassa stagione).'),
  'r1_n': tr('Chambre parentale', 'Main bedroom', 'Camera matrimoniale'), 'r1_d': tr('Lit double.', 'Double bed.', 'Letto matrimoniale.'),
  'r2_n': tr('Chambres 2 & 3', 'Bedrooms 2 & 3', 'Camere 2 & 3'), 'r2_d': tr('Pour les enfants ou les amis.', 'For kids or friends.', 'Per bambini o amici.'),
  'r3_n': tr('Séjour', 'Living room', 'Soggiorno'), 'r3_d': tr('Espace de vie et repas.', 'Living and dining area.', 'Zona giorno e pranzo.'),
  'r4_n': tr('Cuisine', 'Kitchen', 'Cucina'), 'r4_d': tr('Équipements ' + PH3[0], 'Equipment ' + PH3[1], 'Dotazioni ' + PH3[2]),
  'tg_bed': tr('Literie ' + PH3[0], 'Bedding ' + PH3[1], 'Biancheria ' + PH3[2]), 'tg_salon': tr('Salon', 'Lounge', 'Salotto'), 'tg_kitchen': tr('Cuisine', 'Kitchen', 'Cucina'),
  'feat_h2': tr('Des vacances sans souci', 'Stress-free holidays', 'Vacanze senza pensieri'),
  'ft1_t': tr('Remise des clés', 'Key handover', 'Consegna chiavi'), 'ft1_d': tr('Heure convenue sur WhatsApp.', 'Time agreed on WhatsApp.', 'Orario concordato su WhatsApp.'),
  'ft2_t': tr('Tout l’appartement', 'Entire apartment', 'Intero appartamento'), 'ft2_d': tr('Pour vous seuls.', 'All to yourselves.', 'Tutto per voi.'),
  'ft3_t': tr('Plages', 'Beaches', 'Spiagge'), 'ft3_d': tr('Mansoura et Kélibia à proximité.', 'Mansoura and Kélibia nearby.', 'Mansoura e Kélibia vicine.'),
  'ft4_t': tr('Parking', 'Parking', 'Parcheggio'), 'ft4_d': PH3,
  'ft5_t': tr('Climatisation', 'Air-con', 'Aria condizionata'), 'ft5_d': PH3,
  'ft6_t': tr('Wi-Fi', 'Wi-Fi', 'Wi-Fi'), 'ft6_d': PH3,
  'ft7_t': tr('Calendrier', 'Calendar', 'Calendario'), 'ft7_d': tr('Dates libres visibles en ligne (module).', 'Free dates shown online (module).', 'Date libere visibili online (modulo).'),
  'ft8_t': tr('Kélibia', 'Kélibia', 'Kélibia'), 'ft8_d': tr('Fort, port, marché au poisson.', 'Fort, harbour, fish market.', 'Forte, porto, mercato del pesce.'),
  'gal_h2': tr('Kélibia et Mansoura', 'Kélibia and Mansoura', 'Kélibia e Mansoura'),
  'gal_lead': tr('Eau turquoise, fort byzantin et port de pêche. <span class="ph">Photos d’ambiance — à remplacer par vos photos</span>', 'Turquoise water, Byzantine fort and fishing port. <span class="ph">Mood photos — to be replaced with yours</span>', 'Acqua turchese, forte bizantino e porto. <span class="ph">Foto d’atmosfera — da sostituire</span>'),
  'book_extra': tr('Durée minimale de séjour et caution ' + PH3[0] + '<br>Assistant WhatsApp FR/EN/IT activable pour répondre aux demandes 24h/24.',
                   'Minimum stay and deposit ' + PH3[1] + '<br>Optional FR/EN/IT WhatsApp assistant to answer requests 24/7.',
                   'Soggiorno minimo e cauzione ' + PH3[2] + '<br>Assistente WhatsApp FR/EN/IT attivabile 24/7.'),
  'loc_h2': tr('Kélibia, côté Mansoura', 'Kélibia, Mansoura side', 'Kélibia, lato Mansoura'),
  'loc_p': tr('Position approximative sur la carte : adresse exacte communiquée à la réservation ' + PH3[0] + '. Environ 1h45 de Tunis.',
              'Approximate position on the map: exact address given on booking ' + PH3[1] + '. About 1h45 from Tunis.',
              'Posizione approssimativa sulla mappa: indirizzo esatto comunicato alla prenotazione ' + PH3[2] + '. Circa 1h45 da Tunisi.'),
 }))
mans['extra_section'] = ratings_block(mans, [('4.3', 52, 'plurielle.tn', 'https://plurielle.tn/pro/nabeul/appart-lux-s3-a-louer-20318607/')])

for S in (golfe, claud, mans): build(S)
