import sys; import os; sys.path.insert(0,os.path.dirname(os.path.abspath(__file__)))
from gen_guest import build
from urllib.parse import quote

# ---------------- DAR ENESMA ----------------
enesma = dict(slug='dar-enesma', name='Dar Enesma', mark='E', font='playfair',
 title="Dar Enesma — Maison d'hôtes à El Haouaria, Cap Bon (démo)",
 desc="Maison d'hôtes à El Haouaria : 5 chambres-suites vue mer, table d'hôtes, hammam, à 200 m de la plage. Réservation directe.",
 theme=dict(accent='#1b6a86',accent2='#f3c969',soft='#e1f0f5',bg='#fbf8f3',bgalt='#f1ebe1',ink='#0f1d26'),
 wa='21622700243', tel='+21622700243', tel_disp='+216 22 700 243', wa_disp='+216 22 700 243',
 wa_text=quote("Bonjour Dar Enesma, je souhaite des informations pour un séjour."),
 fb='facebook.com/207274199396569', fb_disp='Page Facebook Dar Enesma',
 address="Route du Port, El Haouaria Plage, 8045 El Haouaria, Tunisie",
 map_q=quote('37.03811,11.05454'),
 hero_alt="Côte rocheuse et mer turquoise à El Haouaria", about_img='patio', about_alt="Patio d'inspiration mauresque (photo d'ambiance)",
 facts=['fa','fb','fc','fd'], max_guests=6,
 spaces=['sp1','sp2','sp3','sp4'],
 rooms=[
  dict(k='r1',img='room1',alt='Chambre double (ambiance)',price='80 €',tags=['tg_sea','tg_ac','tg_shower']),
  dict(k='r2',img='room3',alt='Suite familiale avec coin salon (ambiance)',price='95 €',tags=['tg_sea','tg_salon','tg_terr']),
  dict(k='r3',img='room2',alt='Suite familiale (ambiance)',price='95 €',tags=['tg_sea','tg_salon','tg_patio']),
  dict(k='r4',img='g3',alt='Vue mer (ambiance)',price='110 €',tags=['tg_sea','tg_ac','tg_3']),
 ],
 extra_opts=['Chambre n°5'],
 rooms_after='<p class="also" data-i18n="also">+ une 5e chambre-suite <span class="ph">nom et tarif à confirmer</span> · 15 € par personne supplémentaire <span class="ph">à confirmer</span></p>',
 features=[('coffee','ft1'),('drop','ft2'),('food','ft3'),('wifi','ft4'),('car','ft5'),('snow','ft6'),('plane','ft7'),('map','ft8')],
 gallery=[('g5','Épave dans une eau turquoise près d\'El Haouaria'),('hammam','Hammam traditionnel (ambiance)'),('g1','Falaises d\'El Haouaria'),('g2','Crique rocheuse'),('g3','Vue sur l\'île de Zembra'),('g4','Plage d\'El Haouaria'),('g6','Cap Bon vu des hauteurs'),('table','Pâtisseries tunisiennes'),('couscous','Couscous au poisson')],
 rooms_cols='c4',
 t={
  'tagline':("Maison d'hôtes · El Haouaria","Guesthouse · El Haouaria","Casa vacanze · El Haouaria"),
  'nav_rooms':('Chambres','Rooms','Camere'),
  'also':('+ une 5e chambre-suite <span class="ph">nom et tarif à confirmer</span> · 15 € par personne supplémentaire <span class="ph">à confirmer</span>','+ a 5th suite <span class="ph">name and rate to be confirmed</span> · €15 per extra person <span class="ph">to be confirmed</span>','+ una 5a camera-suite <span class="ph">nome e tariffa da confermare</span> · 15 € per persona aggiuntiva <span class="ph">da confermare</span>'),
  'hero_eyebrow':("Maison d'hôtes · El Haouaria, Cap Bon","Guesthouse · El Haouaria, Cap Bon","Casa vacanze · El Haouaria, Cap Bon"),
  'hero_h1':("La brise d'El Haouaria, à deux pas de la mer","The El Haouaria breeze, steps from the sea","La brezza di El Haouaria, a due passi dal mare"),
  'hero_lead':("Cinq chambres-suites avec vue sur la Méditerranée, table d'hôtes, hammam traditionnel et plage de sable à quelques minutes à pied.",
               "Five sea-view suites, a host's table, a traditional hammam and a sandy beach a few minutes' walk away.",
               "Cinque camere-suite vista mare, tavola d'autore, hammam tradizionale e spiaggia di sabbia a pochi minuti a piedi."),
  'fa_b':('5 suites','5 suites','5 suite'),'fa_s':('toutes différentes','all different','tutte diverse'),
  'fb_b':('Vue mer','Sea view','Vista mare'),'fb_s':('depuis chaque chambre','from every room','da ogni camera'),
  'fc_b':('Hammam','Hammam','Hammam'),'fc_s':('traditionnel sur place','traditional, on site','tradizionale in loco'),
  'fd_b':('~200 m','~200 m','~200 m'),'fd_s':('de la plage','to the beach','dalla spiaggia'),
  'about_eyebrow':('La maison','The house','La casa'),
  'about_h2':("« Enesma », la brise en tunisien","“Enesma”, the breeze in Tunisian","“Enesma”, la brezza in tunisino"),
  'about_p1':("En arabe classique, Enesma signifie « l'aura » ; en dialecte tunisien, « la brise ». C'est l'âme d'El Haouaria : le vent, la mer, les sommets et les criques.",
              "In classical Arabic, Enesma means “aura”; in Tunisian dialect, “the breeze”. It is the soul of El Haouaria: wind, sea, peaks and coves.",
              "In arabo classico Enesma significa “l'aura”; in dialetto tunisino “la brezza”. È l'anima di El Haouaria: vento, mare, cime e calette."),
  'about_p2':("Une architecture régionale revisitée, des lignes épurées et une ambiance familiale : ici, on vient se ressourcer entre amis ou en famille, loin de l'agitation, avec une cuisine méditerranéenne faite maison à partir des produits de la région.",
              "Revisited regional architecture, clean lines and a family atmosphere: guests come here to recharge with friends or family, far from the bustle, with home-made Mediterranean cooking based on local produce.",
              "Architettura regionale rivisitata, linee pulite e atmosfera familiare: qui si viene a rigenerarsi tra amici o in famiglia, lontano dal caos, con cucina mediterranea fatta in casa con prodotti locali."),
  'sp1':('Patio mauresque','Moorish patio','Patio moresco'),'sp2':('Salon avec cheminée','Lounge with fireplace','Salotto con camino'),'sp3':('Bibliothèque','Library','Biblioteca'),'sp4':("Table d'hôtes","Host's table","Tavola d'autore"),
  'rooms_eyebrow':('Chambres & suites','Rooms & suites','Camere & suite'),
  'rooms_h2':('Cinq chambres, cinq ambiances','Five rooms, five moods','Cinque camere, cinque atmosfere'),
  'rooms_lead':("Toutes avec salle de bain privative (douche à l'italienne), climatisation, chauffage et vue sur la mer. Petit-déjeuner inclus. Tarifs indicatifs pour 2 personnes / nuit.",
                "All with private bathroom (walk-in shower), air-conditioning, heating and sea view. Breakfast included. Indicative rates for 2 people / night.",
                "Tutte con bagno privato (doccia a filo), aria condizionata, riscaldamento e vista mare. Colazione inclusa. Tariffe indicative per 2 persone / notte."),
  'r1_n':('Berhani — Chambre double','Berhani — Double room','Berhani — Camera doppia'),
  'r1_d':('Une chambre lumineuse et apaisante, idéale pour un séjour en couple.','A bright, soothing room, perfect for couples.','Una camera luminosa e rilassante, ideale per coppie.'),
  'r2_n':('Ghibli — Suite familiale','Ghibli — Family suite','Ghibli — Suite familiare'),
  'r2_d':('Suite spacieuse avec coin salon, pensée pour les familles.','Spacious suite with a seating area, designed for families.','Suite spaziosa con salottino, pensata per le famiglie.'),
  'r3_n':('Jaweni — Suite familiale','Jaweni — Family suite','Jaweni — Suite familiare'),
  'r3_d':('Suite avec patio et coin salon, pour prendre le temps.','Suite with patio and seating area, to slow down.','Suite con patio e salottino, per prendersi il tempo.'),
  'r4_n':('Jbali — Chambre triple','Jbali — Triple room','Jbali — Camera tripla'),
  'r4_d':('Pour trois voyageurs, entre amis ou en famille.','For three travellers, friends or family.','Per tre viaggiatori, amici o famiglia.'),
  'tg_sea':('Vue mer','Sea view','Vista mare'),'tg_ac':('Climatisation','Air-con','Aria condizionata'),'tg_shower':("Douche à l'italienne",'Walk-in shower','Doccia a filo'),
  'tg_salon':('Coin salon','Seating area','Salottino'),'tg_terr':('Terrasse','Terrace','Terrazza'),'tg_patio':('Patio','Patio','Patio'),'tg_3':('3 personnes','3 guests','3 ospiti'),
  'feat_eyebrow':('Services','Services','Servizi'),'feat_h2':('Tout pour un séjour serein','Everything for a relaxed stay','Tutto per un soggiorno sereno'),
  'ft1_t':('Petit-déjeuner inclus','Breakfast included','Colazione inclusa'),'ft1_d':('Fait maison, produits de la région.','Home-made, local produce.','Fatta in casa, prodotti locali.'),
  'ft2_t':('Hammam traditionnel','Traditional hammam','Hammam tradizionale'),'ft2_d':('Accès offert dès 2 nuits <span class="ph">à confirmer</span>','Free from 2 nights <span class="ph">to be confirmed</span>','Gratuito da 2 notti <span class="ph">da confermare</span>'),
  'ft3_t':("Table d'hôtes","Host's dinner","Cena d'autore"),'ft3_d':('Dîner sur réservation.','Dinner on request.','Cena su prenotazione.'),
  'ft4_t':('Wi-Fi gratuit','Free Wi-Fi','Wi-Fi gratuito'),'ft4_d':('Dans toute la maison.','Throughout the house.','In tutta la casa.'),
  'ft5_t':('Parking gratuit','Free parking','Parcheggio gratuito'),'ft5_d':('Sur place.','On site.','In loco.'),
  'ft6_t':('Clim & chauffage','Air-con & heating','Clima & riscaldamento'),'ft6_d':("Confort en toute saison.","Comfort all year round.","Comfort in ogni stagione."),
  'ft7_t':('Navette aéroport','Airport shuttle','Navetta aeroporto'),'ft7_d':('Tunis-Carthage (~100 km), sur demande.','Tunis-Carthage (~100 km), on request.','Tunisi-Cartagine (~100 km), su richiesta.'),
  'ft8_t':('Excursions','Excursions','Escursioni'),'ft8_d':('Kerkouane, grottes romaines, Zembra…','Kerkouane, Roman caves, Zembra…','Kerkouane, grotte romane, Zembra…'),
  'gal_h2':("El Haouaria, entre falaises et criques","El Haouaria, between cliffs and coves","El Haouaria, tra scogliere e calette"),
  'gal_lead':("La pointe du Cap Bon : plages de sable blanc, grottes romaines, vue sur l'île de Zembra. <span class=\"ph\">Photos d'ambiance de la région — à remplacer par vos photos</span>",
              "The tip of Cap Bon: white-sand beaches, Roman caves, views of Zembra island. <span class=\"ph\">Regional mood photos — to be replaced with yours</span>",
              "La punta di Cap Bon: spiagge bianche, grotte romane, vista sull'isola di Zembra. <span class=\"ph\">Foto d'atmosfera della regione — da sostituire</span>"),
  'book_extra':("Arrivée à partir de 14h · départ jusqu'à 11h <span class=\"ph\">à confirmer</span><br>Assistant WhatsApp FR/EN/IT 24h/24 activable : réponses automatiques aux questions fréquentes (prix, dispo, accès).",
                "Check-in from 2 pm · check-out by 11 am <span class=\"ph\">to be confirmed</span><br>Optional 24/7 FR/EN/IT WhatsApp assistant: instant answers to FAQs (rates, availability, directions).",
                "Check-in dalle 14 · check-out entro le 11 <span class=\"ph\">da confermare</span><br>Assistente WhatsApp FR/EN/IT 24/7 attivabile: risposte automatiche alle domande frequenti."),
  'loc_h2':('Au bout du Cap Bon','At the tip of Cap Bon','In cima a Cap Bon'),
  'loc_p':("Route du Port, côté plage d'El Haouaria. Environ 10 km de Kerkouane, 1h30 de Tunis-Carthage.",
           "Route du Port, on the El Haouaria beach side. About 10 km from Kerkouane, 1h30 from Tunis-Carthage airport.",
           "Route du Port, lato spiaggia di El Haouaria. Circa 10 km da Kerkouane, 1h30 dall'aeroporto di Tunisi-Cartagine."),
  'loc_btn':('Itinéraire Google Maps','Directions on Google Maps','Indicazioni su Google Maps'),
 })

# ---------------- BEIT EL HOUTA ----------------
houta = dict(slug='beit-el-houta', name='Beit El Houta', mark='H', font='dmserif',
 title="Beit El Houta — Villa d'art & maison d'hôtes, Aïn Grenz, Kélibia (démo)",
 desc="Beit El Houta : 8 suites uniques, plage, suite avec piscine privative, à Aïn Grenz (Kélibia). Réservation directe.",
 theme=dict(accent='#b9543b',accent2='#f6c667',soft='#f8e6de',bg='#fdf8f2',bgalt='#f5ebe0',ink='#241510'),
 wa='21626638631', tel='+21626638631', tel_disp='+216 26 638 631', wa_disp='+216 26 638 631',
 wa_text=quote("Bonjour Beit El Houta, je souhaite des informations pour un séjour."),
 fb='www.facebook.com/1619073021668031', fb_disp='Page Facebook Beit El Houta',
 address="Aïn Grenz, 8090 Kélibia, Tunisie",
 map_q=quote('Beit El Houta, Ain Grenz, Kelibia'),
 hero_alt="Plage de sable blanc à Kélibia", about_img='tent', about_alt="Salon aux tissus colorés (photo d'ambiance)",
 facts=['fa','fb','fc','fd'], max_guests=6, spaces=['sp1','sp2','sp3','sp4'],
 rooms=[
  dict(k='r1',img='pool',alt='Piscine face à la mer (ambiance)',price='400 DT',tags=['tg_pool','tg_sea','tg_terr']),
  dict(k='r2',img='suite2',alt='Suite lumineuse (ambiance)',price='250 DT',tags=['tg_fire','tg_ac','tg_sea2']),
  dict(k='r3',img='suite1',alt='Cour traditionnelle (ambiance)',price='250 DT',tags=['tg_fire','tg_ac','tg_trad']),
  dict(k='r4',img='suite3',alt='Chambre (ambiance)',price='—',tags=['tg_bath','tg_ac','tg_fire']),
 ],
 extra_opts=['Beit Abla','Beit Antar','Bouboucha',"L'Atelier"],
 features=[('waves','ft1'),('sun','ft2'),('fire','ft3'),('snow','ft4'),('home','ft5'),('chat','ft6'),('calendar','ft7'),('map','ft8')],
 gallery=[('g1','Littoral de Kélibia'),('g2','Rochers et eau claire'),('g3','Plage de Kélibia'),('g4','Vue du fort de Kélibia sur la mer'),('g5','Barque sur la plage'),('g6','Nasses de pêcheurs'),('door','Porte bleue tunisienne'),('tent','Tente et tissus colorés'),('suite1','Cour traditionnelle colorée')],
 rooms_cols='c4',
 rooms_after='<p class="also" data-i18n="also">Également : <b>Beit Abla</b>, <b>Beit Antar</b>, <b>Bouboucha</b> et <b>L\'Atelier</b> (avec kitchenette). <span class="ph">tarifs à confirmer</span></p>',
 t={
  'tagline':("Villa d'art · Aïn Grenz, Kélibia","Art villa · Aïn Grenz, Kélibia","Villa d'arte · Aïn Grenz, Kélibia"),
  'nav_rooms':('Suites','Suites','Suite'),
  'hero_eyebrow':("Maison d'hôtes · plage d'Aïn Grenz, Kélibia","Guesthouse · Aïn Grenz beach, Kélibia","Casa vacanze · spiaggia di Aïn Grenz, Kélibia"),
  'hero_h1':("Beit El Houta, la maison du poisson, face à la mer","Beit El Houta, the fish house, facing the sea","Beit El Houta, la casa del pesce, sul mare"),
  'hero_lead':("Huit suites aux couleurs du monde, une plage de sable fin et une suite avec piscine privative. Un dépaysement total, loin de l'ambiance aseptisée des hôtels.",
               "Eight suites in colours from around the world, a fine-sand beach and a suite with its own private pool. A true escape, far from standard hotels.",
               "Otto suite dai colori del mondo, una spiaggia di sabbia fine e una suite con piscina privata. Una vera evasione, lontano dagli hotel standard."),
  'fa_b':('8 suites','8 suites','8 suite'),'fa_s':('toutes uniques','each one unique','tutte uniche'),
  'fb_b':('Plage','Beach','Spiaggia'),'fb_s':("d'Aïn Grenz","at Aïn Grenz","di Aïn Grenz"),
  'fc_b':('Piscine','Pool','Piscina'),'fc_s':('privative (suite El Houta)','private (El Houta suite)','privata (suite El Houta)'),
  'fd_b':('Cheminées','Fireplaces','Camini'),'fd_s':('dans les suites','in the suites','nelle suite'),
  'about_eyebrow':('La maison','The house','La casa'),
  'about_h2':("Une villa d'art où chaque objet raconte un voyage","An art villa where every object tells a journey","Una villa d'arte dove ogni oggetto racconta un viaggio"),
  'about_p1':("À Aïn Grenz, Nejib et Ichrak vous reçoivent dans un cadre unique aux couleurs du monde entier, imprégné des voyages et des coups de cœur du maître des lieux.",
              "In Aïn Grenz, Nejib and Ichrak welcome you to a one-of-a-kind setting in colours from all over the world, shaped by the owner's travels and favourite finds.",
              "Ad Aïn Grenz, Nejib e Ichrak vi accolgono in un luogo unico dai colori di tutto il mondo, ispirato dai viaggi e dalle passioni del padrone di casa."),
  'about_p2':("Seuls, en couple ou en famille : entre le Salon Africain, la Tente Bédouine, le Salon Bambou et la plage, la tranquillité est le maître mot.",
              "Alone, as a couple or with family: between the African Lounge, the Bedouin Tent, the Bamboo Lounge and the beach, tranquillity is the rule.",
              "Da soli, in coppia o in famiglia: tra il Salotto Africano, la Tenda Beduina, il Salotto Bambù e la spiaggia, la tranquillità è la regola."),
  'sp1':('Salon Africain','African Lounge','Salotto Africano'),'sp2':('Tente Bédouine','Bedouin Tent','Tenda Beduina'),'sp3':('Salon Bambou','Bamboo Lounge','Salotto Bambù'),'sp4':('Plage','Beach','Spiaggia'),
  'rooms_eyebrow':('Les suites','The suites','Le suite'),
  'rooms_h2':('À chaque « Beit » sa personnalité','Every “Beit” has its own personality','Ogni “Beit” ha la sua personalità'),
  'rooms_lead':("Toutes équipées de cheminée, climatisation, télévision et salle d'eau. Tarifs indicatifs publiés en ligne, par nuit pour 2 personnes.",
                "All with fireplace, air-conditioning, TV and bathroom. Indicative rates published online, per night for 2 people.",
                "Tutte con camino, aria condizionata, TV e bagno. Tariffe indicative pubblicate online, a notte per 2 persone."),
  'r1_n':('Suite El Houta','El Houta Suite','Suite El Houta'),
  'r1_d':("La signature de la maison : piscine privative et terrasse avec vue sur mer.","The house signature: private pool and sea-view terrace.","La firma della casa: piscina privata e terrazza vista mare."),
  'r2_n':('Suite Flouka','Flouka Suite','Suite Flouka'),'r2_d':("Pour les amoureux de l'air marin.","For lovers of sea air.","Per chi ama l'aria di mare."),
  'r3_n':('Suite Khomsa','Khomsa Suite','Suite Khomsa'),'r3_d':('Les charmes de la tradition tunisienne.','The charm of Tunisian tradition.','Il fascino della tradizione tunisina.'),
  'r4_n':('Suite Indienne','Indian Suite','Suite Indiana'),'r4_d':('Une nuit inoubliable, baignoire au milieu de la chambre.','An unforgettable night, with a bathtub in the middle of the room.','Una notte indimenticabile, con vasca al centro della camera.'),
  'tg_pool':('Piscine privative','Private pool','Piscina privata'),'tg_sea':('Vue mer','Sea view','Vista mare'),'tg_terr':('Terrasse','Terrace','Terrazza'),
  'tg_fire':('Cheminée','Fireplace','Camino'),'tg_ac':('Climatisation','Air-con','Aria condizionata'),'tg_sea2':('Esprit marin','Seaside mood','Spirito marino'),
  'tg_trad':('Déco traditionnelle','Traditional décor','Arredo tradizionale'),'tg_bath':('Baignoire','Bathtub','Vasca'),
  'also':("Également : <b>Beit Abla</b>, <b>Beit Antar</b>, <b>Bouboucha</b> et <b>L'Atelier</b> (avec kitchenette). <span class=\"ph\">tarifs à confirmer</span>",
          "Also: <b>Beit Abla</b>, <b>Beit Antar</b>, <b>Bouboucha</b> and <b>L'Atelier</b> (with kitchenette). <span class=\"ph\">rates to be confirmed</span>",
          "Inoltre: <b>Beit Abla</b>, <b>Beit Antar</b>, <b>Bouboucha</b> e <b>L'Atelier</b> (con angolo cottura). <span class=\"ph\">tariffe da confermare</span>"),
  'feat_eyebrow':('Expérience','Experience','Esperienza'),'feat_h2':('Le temps ralentit à Aïn Grenz','Time slows down in Aïn Grenz','Ad Aïn Grenz il tempo rallenta'),
  'ft1_t':('Plage','Beach','Spiaggia'),'ft1_d':("Sable fin et eau claire d'Aïn Grenz.","Fine sand and clear water.","Sabbia fine e acqua limpida."),
  'ft2_t':('Piscine privative','Private pool','Piscina privata'),'ft2_d':('Dans la suite El Houta.','In the El Houta suite.','Nella suite El Houta.'),
  'ft3_t':('Cheminées','Fireplaces','Camini'),'ft3_d':("Pour les soirées d'hiver.","For winter evenings.","Per le serate d'inverno."),
  'ft4_t':('Climatisation','Air-con','Aria condizionata'),'ft4_d':('Dans toutes les suites.','In every suite.','In tutte le suite.'),
  'ft5_t':('Espaces communs','Shared spaces','Spazi comuni'),'ft5_d':('Salon Africain, Tente Bédouine, Salon Bambou.','African Lounge, Bedouin Tent, Bamboo Lounge.','Salotto Africano, Tenda Beduina, Salotto Bambù.'),
  'ft6_t':('Réponse rapide','Fast replies','Risposte rapide'),'ft6_d':('WhatsApp FR/EN/IT, même hors horaires <span class="ph">option</span>','WhatsApp FR/EN/IT, even after hours <span class="ph">option</span>','WhatsApp FR/EN/IT, anche fuori orario <span class="ph">opzione</span>'),
  'ft7_t':('Réservation 24h/24','Book 24/7','Prenota 24/7'),'ft7_d':('Plus besoin d\'appeler entre 10h et 14h.','No need to call between 10am and 2pm.','Non serve più chiamare tra le 10 e le 14.'),
  'ft8_t':('Kélibia à découvrir','Explore Kélibia','Scopri Kélibia'),'ft8_d':('Fort, port de pêche, Mansoura…','Fort, fishing port, Mansoura…','Forte, porto, Mansoura…'),
  'gal_h2':('Kélibia, côté mer','Kélibia, by the sea','Kélibia, lato mare'),
  'gal_lead':("Plages, fort byzantin et port de pêche. <span class=\"ph\">Photos d'ambiance de la région — à remplacer par vos photos</span>","Beaches, fort and fishing port. <span class=\"ph\">Regional mood photos — to be replaced with yours</span>","Spiagge, forte e porto. <span class=\"ph\">Foto d'atmosfera — da sostituire</span>"),
  'book_extra':("Aujourd'hui, les réservations se font par téléphone de 10h à 14h et de 16h à 18h. Avec ce site, vos clients envoient leur demande à toute heure, et vous confirmez quand vous voulez.",
                "Today, bookings are taken by phone 10am–2pm and 4pm–6pm. With this site, guests can send a request any time and you confirm when it suits you.",
                "Oggi le prenotazioni si fanno per telefono dalle 10 alle 14 e dalle 16 alle 18. Con questo sito gli ospiti inviano la richiesta a qualsiasi ora."),
  'loc_h2':('Sur la plage d\'Aïn Grenz','On Aïn Grenz beach','Sulla spiaggia di Aïn Grenz'),
  'loc_p':("À Aïn Grenz, au nord de Kélibia, au cœur du Cap Bon. Environ 1h45 de Tunis.","In Aïn Grenz, north of Kélibia, in the heart of Cap Bon. About 1h45 from Tunis.","Ad Aïn Grenz, a nord di Kélibia, nel cuore di Cap Bon. Circa 1h45 da Tunisi."),
  'loc_btn':('Itinéraire Google Maps','Directions on Google Maps','Indicazioni su Google Maps'),
 })

# ---------------- L'HIRONDELLE ----------------
hir = dict(slug='hirondelle-kelibia', name="L'Hirondelle de Kélibia", mark='H', font='fraunces',
 title="L'Hirondelle de Kélibia — Chez Amou · Maison d'hôtes & restaurant (démo)",
 desc="Maison d'hôtes et restaurant en bord de mer à Kélibia (Aïn Grenz) : 7 suites climatisées, patio à arcades, cuisine maison. Réservation directe.",
 theme=dict(accent='#1d5fa6',accent2='#ffc15e',soft='#e3edf8',bg='#f8fafc',bgalt='#eef3f8',ink='#0d1b2e'),
 wa='21696194187', tel='+21623105706', tel_disp='+216 23 105 706', wa_disp='+216 96 194 187',
 email='hirondelledekelibia@gmail.com',
 wa_text=quote("Bonjour L'Hirondelle (Chez Amou), je souhaite des informations pour un séjour."),
 address="Avenue de l'Environnement (Aïn Grenz), 8090 Kélibia, Tunisie",
 map_q=quote("L'Hirondelle de Kelibia Chez Amou, Ain Grenz, Kelibia"),
 hero_alt="Vue sur la mer et le port de Kélibia depuis le fort", about_img='patio', about_alt="Patio tunisien (photo d'ambiance)",
 facts=['fa','fb','fc','fd'], max_guests=8, spaces=['sp1','sp2','sp3','sp4'],
 rooms=[
  dict(k='r1',img='door',alt='Suite classique (ambiance)',price='170 DT',tags=['tg_2ch','tg_ac','tg_fridge']),
  dict(k='r2',img='suite',alt='Grande suite (ambiance)',price='— DT',tags=['tg_2ch','tg_salon','tg_bath']),
 ],
 rooms_cols='',
 features=[('waves','ft1'),('food','ft2'),('coffee','ft3'),('snow','ft4'),('key','ft5'),('home','ft6'),('chat','ft7'),('map','ft8')],
 gallery=[('g1','Barques au port de Kélibia'),('hero','Mer et fort de Kélibia'),('g2','Port de Kélibia vu du fort'),('g3','Fort de Kélibia'),('g4','Plage au coucher du soleil'),('fish','Sardines grillées'),('couscous','Couscous aux sardines'),('sweets','Pâtisseries tunisiennes'),('g5','Kélibia et son port')],
 extra_section='',
 t={
  'tagline':("Chez Amou · Maison d'hôtes & restaurant","Chez Amou · Guesthouse & restaurant","Chez Amou · Casa vacanze & ristorante"),
  'nav_rooms':('Suites','Suites','Suite'),
  'hero_eyebrow':("Maison d'hôtes & restaurant · Kélibia, Cap Bon","Guesthouse & restaurant · Kélibia, Cap Bon","Casa vacanze & ristorante · Kélibia, Cap Bon"),
  'hero_h1':("L'Hirondelle de Kélibia, chez Amou","L'Hirondelle de Kélibia, at Amou's","L'Hirondelle de Kélibia, da Amou"),
  'hero_lead':("Une demeure familiale typiquement tunisienne en bord de mer : suites climatisées pour 4 personnes, patio à arcades et restaurant maison.",
               "A typical Tunisian family home by the sea: air-conditioned suites for up to 4, an arcaded patio and a home-style restaurant.",
               "Una tipica casa di famiglia tunisina sul mare: suite climatizzate fino a 4 persone, patio con archi e ristorante casalingo."),
  'fa_b':('7 suites','7 suites','7 suite'),'fa_s':('climatisées','air-conditioned','climatizzate'),
  'fb_b':('4 pers.','4 guests','4 ospiti'),'fb_s':('par suite, 2 chambres','per suite, 2 bedrooms','per suite, 2 camere'),
  'fc_b':('dès 170 DT','from 170 TND','da 170 TND'),'fc_s':('par suite / nuit*','per suite / night*','per suite / notte*'),
  'fd_b':('Restaurant','Restaurant','Ristorante'),'fd_s':('sur place','on site','in loco'),
  'about_eyebrow':('La maison','The house','La casa'),
  'about_h2':('Comme à la maison, au bord de la mer','Like home, by the sea','Come a casa, sul mare'),
  'about_p1':("L'Hirondelle est une maison familiale tunisienne qui propose des suites à louer en bord de mer, à Aïn Grenz.",
              "L'Hirondelle is a Tunisian family house offering seaside suites in Aïn Grenz.",
              "L'Hirondelle è una casa di famiglia tunisina che offre suite sul mare ad Aïn Grenz."),
  'about_p2':("Les hébergements sont à l'étage, desservis par une entrée indépendante et un joli patio avec arcades. Au rez-de-chaussée, le restaurant accueille petits-déjeuners et repas.",
              "The suites are upstairs, with an independent entrance and a pretty arcaded patio. Downstairs, the restaurant serves breakfast and meals.",
              "Le suite sono al piano superiore, con ingresso indipendente e un bel patio con archi. Al piano terra il ristorante serve colazioni e pasti."),
  'sp1':('Entrée indépendante','Private entrance','Ingresso indipendente'),'sp2':('Patio à arcades','Arcaded patio','Patio con archi'),'sp3':('Restaurant','Restaurant','Ristorante'),'sp4':('Bord de mer','Seafront','Fronte mare'),
  'rooms_eyebrow':('Les suites','The suites','Le suite'),
  'rooms_h2':('Deux formules, jusqu\'à 4 personnes','Two options, up to 4 guests','Due soluzioni, fino a 4 ospiti'),
  'rooms_lead':("Toutes climatisées, sans cuisine. Tarif par suite et par nuitée (max 4 personnes), hors repas.",
                "All air-conditioned, no kitchen. Rate per suite per night (max 4 guests), meals not included.",
                "Tutte climatizzate, senza cucina. Tariffa per suite a notte (max 4 ospiti), pasti esclusi."),
  'r1_n':('Suite classique (×6)','Classic suite (×6)','Suite classica (×6)'),
  'r1_d':('2 chambres séparées avec lits doubles, réfrigérateur, salle de douche et WC.','2 separate bedrooms with double beds, fridge, shower room and WC.','2 camere separate con letto matrimoniale, frigo, doccia e WC.'),
  'r2_n':('Grande suite','Grand suite','Grande suite'),
  'r2_d':('2 chambres doubles, grand salon TV privé avec balcon, salle de bain avec baignoire.','2 double bedrooms, large private TV lounge with balcony, bathroom with bathtub.','2 camere matrimoniali, ampio salotto TV privato con balcone, bagno con vasca.'),
  'tg_2ch':('2 chambres','2 bedrooms','2 camere'),'tg_ac':('Climatisation','Air-con','Aria condizionata'),'tg_fridge':('Frigo','Fridge','Frigo'),
  'tg_salon':('Salon + balcon','Lounge + balcony','Salotto + balcone'),'tg_bath':('Baignoire','Bathtub','Vasca'),
  'feat_eyebrow':('Services','Services','Servizi'),'feat_h2':('Simple, familial, pratique','Simple, friendly, practical','Semplice, familiare, pratico'),
  'ft1_t':('Bord de mer','Seafront','Fronte mare'),'ft1_d':("Plages d'Aïn Grenz.","Aïn Grenz beaches.","Spiagge di Aïn Grenz."),
  'ft2_t':('Restaurant maison','Home restaurant','Ristorante casalingo'),'ft2_d':('Repas sur réservation.','Meals on request.','Pasti su prenotazione.'),
  'ft3_t':('Petit-déjeuner','Breakfast','Colazione'),'ft3_d':('Dès 13 DT, sur réservation <span class="ph">à confirmer</span>','From 13 TND, on request <span class="ph">to be confirmed</span>','Da 13 TND, su prenotazione <span class="ph">da confermare</span>'),
  'ft4_t':('Climatisation','Air-con','Aria condizionata'),'ft4_d':('Dans toutes les suites.','In every suite.','In tutte le suite.'),
  'ft5_t':('Entrée indépendante','Private entrance','Ingresso indipendente'),'ft5_d':('Liberté totale.','Total freedom.','Massima libertà.'),
  'ft6_t':('Idéal familles','Great for families','Ideale per famiglie'),'ft6_d':('2 chambres par suite.','2 bedrooms per suite.','2 camere per suite.'),
  'ft7_t':('WhatsApp','WhatsApp','WhatsApp'),'ft7_d':('Réponse en FR/EN/IT <span class="ph">assistant option</span>','Replies in FR/EN/IT <span class="ph">assistant option</span>','Risposte in FR/EN/IT <span class="ph">opzione</span>'),
  'ft8_t':('Kélibia','Kélibia','Kélibia'),'ft8_d':('Fort, port, plages de Mansoura.','Fort, port, Mansoura beaches.','Forte, porto, spiagge di Mansoura.'),
  'gal_h2':('Kélibia, ses barques et ses saveurs','Kélibia, its boats and flavours','Kélibia, le sue barche e i suoi sapori'),
  'gal_lead':("Port de pêche, fort et cuisine de la mer. <span class=\"ph\">Photos d'ambiance — à remplacer par vos photos et vos plats</span>","Fishing port, fort and seafood. <span class=\"ph\">Mood photos — to be replaced with your photos and dishes</span>","Porto, forte e cucina di mare. <span class=\"ph\">Foto d'atmosfera — da sostituire</span>"),
  'book_extra':("* Tarif « à partir de 170 DT (≈ 55 €) par suite et par nuit » repris de votre site actuel <span class=\"ph\">à confirmer pour 2027</span>. Demande aussi possible par email.",
                "* “From 170 TND (≈ €55) per suite per night” taken from your current site <span class=\"ph\">to be confirmed for 2027</span>. Requests by email also possible.",
                "* “Da 170 TND (≈ 55 €) per suite a notte” ripreso dal vostro sito attuale <span class=\"ph\">da confermare per il 2027</span>. Richieste anche via email."),
  'loc_h2':('À Aïn Grenz, Kélibia','In Aïn Grenz, Kélibia','Ad Aïn Grenz, Kélibia'),
  'loc_p':("Avenue de l'Environnement, quartier d'Aïn Grenz, à Kélibia. Environ 1h45 de Tunis.","Avenue de l'Environnement, Aïn Grenz area, Kélibia. About 1h45 from Tunis.","Avenue de l'Environnement, zona Aïn Grenz, Kélibia. Circa 1h45 da Tunisi."),
  'loc_btn':('Itinéraire Google Maps','Directions on Google Maps','Indicazioni su Google Maps'),
 })

# restaurant section for Hirondelle
hir['extra_section'] = '''<section class="section alt" id="restaurant"><div class="container grid-2">
<div class="about-img reveal" style="aspect-ratio:4/3"><img src="img/fish2.jpg" alt="Poisson grillé (photo d'ambiance)" loading="lazy"></div>
<div class="reveal"><span class="eyebrow" data-i18n="rest_e">Le restaurant</span><h2 data-i18n="rest_h">La table de Chez Amou</h2><p class="lead" data-i18n="rest_p">Petits-déjeuners et repas servis sur place, pour les hôtes de la maison comme pour les gourmands de passage.</p>
<ul class="menu-list"><li><b data-i18n="m1">Petit-déjeuner</b><span data-i18n="m1p">dès 13 DT</span></li><li><b data-i18n="m2">Poisson du jour</b><span class="ph" data-i18n="ph">à confirmer</span></li><li><b data-i18n="m3">Plat tunisien maison</b><span class="ph" data-i18n="ph">à confirmer</span></li><li><b data-i18n="m4">Dessert maison</b><span class="ph" data-i18n="ph">à confirmer</span></li></ul>
<p class="form-note" style="margin-top:.8rem" data-i18n="m_note">Exemple de carte : à remplacer par votre menu réel. Menu QR et commande WhatsApp activables.</p></div></div></section>'''
hir['t'].update({
 'rest_e':('Le restaurant','The restaurant','Il ristorante'),'rest_h':('La table de Chez Amou','The Chez Amou table','La tavola di Chez Amou'),
 'rest_p':("Petits-déjeuners et repas servis sur place, pour les hôtes de la maison comme pour les gourmands de passage.","Breakfast and meals served on site, for guests and passing food lovers alike.","Colazioni e pasti serviti in loco, per gli ospiti e per i buongustai di passaggio."),
 'm1':('Petit-déjeuner','Breakfast','Colazione'),'m1p':('dès 13 DT','from 13 TND','da 13 TND'),
 'm2':('Poisson du jour','Catch of the day','Pesce del giorno'),'m3':('Plat tunisien maison','Home-made Tunisian dish','Piatto tunisino fatto in casa'),'m4':('Dessert maison','Home-made dessert','Dolce fatto in casa'),
 'm_note':("Exemple de carte : à remplacer par votre menu réel. Menu QR et commande WhatsApp activables.","Sample menu: to be replaced with your real menu. QR menu and WhatsApp ordering available.","Menu di esempio: da sostituire con il vostro menu reale. Menu QR e ordini WhatsApp attivabili."),
})
for S in (enesma,houta,hir): build(S)
